---
title: "Cormotifcluster_analysis"
author: "ERM"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Import libraries, message=FALSE, warning=FALSE}
library(tidyverse)
library(gprofiler2)
library(readr)
library(BiocGenerics)
library(gridExtra)
library(VennDiagram)
library(kableExtra)
library(scales)
library(ggVennDiagram)

```

```{r Import data, message=FALSE, warning=FALSE, include=FALSE}

DEG_cormotif <- readRDS("data/DEG_cormotif.RDS")
motif1_NR <- DEG_cormotif$motif1_NR
motif3_TI <- DEG_cormotif$motif3_TI
motif4_LR <- DEG_cormotif$motif4_LR
motif5_ER <- DEG_cormotif$motif5_ER
  
backGL <- read.csv("data/backGL.txt")
NRresp <- read_csv("data/cormotif_NRset.txt")

```

##motif1 No response genes

```{r noresponse data motif1, echo=FALSE, message=FALSE, warning=FALSE}
gostrescoNR <- gost(query = motif1_NR , 
                      organism = "hsapiens",
                      ordered_query = FALSE,
                      domain_scope = "custom",
                      measure_underrepresentation = FALSE,
                      evcodes = FALSE,
                      user_threshold = 0.05,
                      correction_method = c("fdr"),
                      custom_bg = backGL$ENTREZID,
                      sources=c("GO:BP", "KEGG"))
cormotifNRcluster <- gostplot(gostrescoNR, capped = FALSE, interactive = TRUE)
cormotifNRcluster

# (gostres$result$p_value)
tableNR <- gostrescoNR$result %>%
  dplyr::select(c(source, term_id, term_name,intersection_size, term_size, p_value)) #%>% 
  # mutate_at(.cols = 6, .funs= scientific_format()) %>% 
  # kable(.,) %>% 
  # kable_paper("striped", full_width = FALSE) %>%  
  # kable_styling(full_width = FALSE, position = "left",bootstrap_options = c("striped","hover"))
  tableNR%>% 
  mutate_at(.cols = 6, .funs= scientific_format()) %>% 
  kable(.,) %>% 
  kable_paper("striped", full_width = FALSE) %>%  
  kable_styling(full_width = FALSE, position = "left",bootstrap_options = c("striped","hover")) %>% 
  scroll_box(width = "100%", height = "400px")
  write.csv(tableNR,"output/tableNR.csv")
##GO:BP  
  tableNR %>% dplyr::filter(source=="GO:BP") %>% 
    dplyr::select(p_value,term_name,intersection_size) %>%
    slice_min(., n=10 ,order_by=p_value) %>%
    mutate(log_val = -log10(p_value)) %>%
   # slice_max(., n=10,order_by = p_value) %>%
   ggplot(., aes(x = log_val, y =reorder(term_name,p_value),col=intersection_size)) +
    geom_point(aes(size = intersection_size)) +
    ggtitle('No response enriched GO:BP terms') +
    xlab("-log 10 (p-value)")+
    guides(col="none", size=guide_legend(title = "# of intersected \n terms"))+
    ylab("GO: BP term")+
    scale_y_discrete(labels = wrap_format(30))+
      theme_bw()+
    theme(plot.title = element_text(size = rel(1.5), hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.line = element_line(linewidth = 1.5),
        axis.text = element_text(size = 10, color = "black", angle = 0),
        strip.text.x = element_text(size = 15, color = "black", face = "bold"))
##kegg
  
  tableNR %>% 
    dplyr::filter(source!="GO:BP") %>% 
    dplyr::select(p_value,term_name,intersection_size) %>%
    slice_min(., n=15 ,order_by=p_value) %>%
    mutate(log_val = -log10(p_value)) %>%
   # slice_max(., n=10,order_by = p_value) %>%
   ggplot(., aes(x = log_val, 
                 y =reorder(term_name,p_value),
                 col=intersection_size)) +
    geom_point(aes(size = intersection_size, col="red")) +
    ggtitle('No response enriched KEGG terms') +
    scale_y_discrete(labels = wrap_format(30))+
    guides(col="none", size=guide_legend(title = "# of intersected \n terms"))+
    xlab("-log 10 (p-value)")+
    ylab("KEGG term")+
      theme_bw()+
    theme(plot.title = element_text(size = rel(1.5), hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.line = element_line(linewidth = 1.5),
        axis.text = element_text(size = 10, color = "black", angle = 0),
        strip.text.x = element_text(size = 15, color = "black", face = "bold"))

  
  
```

##motif 4 Late response Top2inhibitors

```{r Top2iLR motif4 set, echo=FALSE, message=FALSE, warning=FALSE}


gostresTop2bi_LR <- gost(query = c(motif4_LR),  
                      organism = "hsapiens",
                      ordered_query = FALSE,
                      domain_scope = "custom",
                      measure_underrepresentation = FALSE,
                      evcodes = FALSE,
                      user_threshold = 0.01,
                      correction_method = c("fdr"),
                      custom_bg = backGL$ENTREZID,
                      sources=c("GO:BP", "KEGG"))
cormotifrespTop2bi_LR <- gostplot(gostresTop2bi_LR, capped = FALSE, interactive = TRUE)
cormotifrespTop2bi_LR


tabletop2Bi_LR <- gostresTop2bi_LR$result %>%
  dplyr::select(c(source, term_id, term_name,intersection_size, term_size, p_value)) 
  
tabletop2Bi_LR%>% 
  mutate_at(.cols = 6, .funs= scientific_format()) %>% 
  kable(.,) %>% 
  kable_paper("striped", full_width = FALSE) %>%  
  kable_styling(full_width = FALSE, position = "left",bootstrap_options = c("striped","hover")) %>% 
  scroll_box(width = "100%", height = "400px")
 write.csv(tabletop2Bi_LR,"output/tabletop2Bi_LR.csv") 
  
  tabletop2Bi_LR %>% dplyr::filter(source=="GO:BP") %>% 
    dplyr::select(p_value,term_name,intersection_size) %>%
    slice_min(., n=10 ,order_by=p_value) %>%
    mutate(log_val = -log10(p_value)) %>%
   # slice_max(., n=10,order_by = p_value) %>%
   ggplot(., aes(x = log_val, y =reorder(term_name,log_val), col= intersection_size)) +
    geom_point(aes(size = intersection_size)) +
    scale_y_discrete(labels = wrap_format(30))+
    guides(col="none", size=guide_legend(title = "# of intersected \n terms"))+
    ggtitle('Late Response enriched GO:BP terms') +
    xlab("-log 10 (p-value)")+
    ylab("GO: BP term")+
      theme_bw()+
    theme(plot.title = element_text(size = rel(1.5), hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.line = element_line(linewidth = 1.5),
        axis.text = element_text(size = 10, color = "black", angle = 0),
        strip.text.x = element_text(size = 15, color = "black", face = "bold"))

  
 tabletop2Bi_LR %>% 
    dplyr::filter(source!="GO:BP") %>% 
    dplyr::select(p_value,term_name,intersection_size) %>%
    slice_min(., n=20 ,order_by=p_value) %>%
    mutate(log_val = -log10(p_value)) %>%
   # slice_max(., n=10,order_by = p_value) %>%
   ggplot(., aes(x = log_val, y =reorder(term_name,p_value),col=intersection_size)) +
    geom_point(aes(size = intersection_size, col="red")) +
   scale_y_discrete(labels = wrap_format(30))+
    guides(col="none", size=guide_legend(title = "# of intersected \n terms"))+
    ggtitle('Late Response enriched KEGG terms') +
    xlab("-log 10 (p-value)")+
    ylab("KEGG term")+
      theme_bw()+
 theme(plot.title = element_text(size = rel(1.5), hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.line = element_line(linewidth = 1.5),
        axis.text = element_text(size = 10, color = "black", angle = 0),
        strip.text.x = element_text(size = 15, color = "black", face = "bold"))
  


```

##motif 5 Early Response Top2 inhibitors

```{r Top2iER set motif5, echo=FALSE, message=FALSE, warning=FALSE}


gostresTop2bi_ER <- gost(query = c(motif5_ER),  
                      organism = "hsapiens",
                      ordered_query = FALSE,
                      domain_scope = "custom",
                      measure_underrepresentation = FALSE,
                      evcodes = FALSE,
                      user_threshold = 0.05,
                      correction_method = c("fdr"),
                      custom_bg = backGL$ENTREZID,
                      sources=c("GO:BP", "KEGG"))
cormotifrespTop2bi_ER <- gostplot(gostresTop2bi_ER, capped = FALSE, interactive = TRUE)

cormotifrespTop2bi_ER %>% 
  mutate_at(.cols = 6, .funs= scientific_format()) %>% 
  kable(.,) %>% 
  kable_paper("striped", full_width = FALSE) %>%  
  kable_styling(full_width = FALSE, position = "left",bootstrap_options = c("striped","hover")) %>% 
  scroll_box(width = "100%", height = "400px")
 
tabletop2Bi_ER <- gostresTop2bi_ER$result %>%
  dplyr::select(c(source, term_id, term_name,intersection_size, term_size, p_value)) 
write.csv(tabletop2Bi_ER,"output/tabletop2Bi_ER.csv")
#%>% 
  # mutate_at(.cols = 6, .funs= scientific_format()) %>% 
  # kable(.,) %>% 
  # kable_paper("striped", full_width = FALSE) %>%  
  # kable_styling(full_width = FALSE, position = "left",bootstrap_options = c("striped","hover"))
tabletop2Bi_ER %>% 
  mutate_at(.cols = 6, .funs= scientific_format()) %>% 
  kable(.,) %>% 
  kable_paper("striped", full_width = FALSE) %>%  
  kable_styling(full_width = FALSE, position = "left",bootstrap_options = c("striped","hover")) %>% 
  scroll_box(width = "100%", height = "400px")
  
  tabletop2Bi_ER %>% 
    dplyr::filter(source=="GO:BP") %>% 
    dplyr::select(p_value,term_name,intersection_size) %>%
    slice_min(., n=13 ,order_by=p_value) %>%
    mutate(log_val = -log10(p_value)) %>%
   # slice_max(., n=10,order_by = p_value) %>%
   ggplot(., aes(x = log_val, y =reorder(term_name,p_value),col=intersection_size)) +
    geom_point(aes(size = intersection_size)) +
    scale_y_discrete(labels = wrap_format(35))+
    guides(col="none", size=guide_legend(title = "# of intersected \n terms"))+
    ggtitle('Early Response enriched GO:BP terms') +
    xlab("-log 10 (p-value)")+
    ylab("GO: BP term")+
      theme_bw()+
 theme(plot.title = element_text(size = rel(1.5), hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.line = element_line(linewidth = 1.5),
        axis.text = element_text(size = 8, color = "black", angle = 0),
        strip.text.x = element_text(size = 15, color = "black", face = "bold"))
  
tabletop2Bi_ER %>% 
    dplyr::filter(source!="GO:BP") %>% 
    dplyr::select(p_value,term_name,intersection_size) %>%
    slice_min(., n=15 ,order_by=p_value) %>%
    mutate(log_val = -log10(p_value)) %>%
   ggplot(., aes(x = log_val,y = reorder(term_name,p_value),
                 col=intersection_size)) +
  geom_point(aes(size = intersection_size, col="red")) +
  scale_y_discrete(labels = wrap_format(35))+
  guides(col="none", 
         size=guide_legend(title ="# of intersected \n terms"))+
  ggtitle('Early Response enriched KEGG terms') +
  xlab("-log 10 (p-value)")+
  ylab("KEGG term")+
  theme_bw()+
  theme(plot.title = element_text(size = rel(1.5), hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.line = element_line(linewidth = 1.5),
        axis.text = element_text(size = 9, color = "black", angle = 0),
        strip.text.x = element_text(size = 15, color = "black", face = "bold"))


```

##motif 3 time independent response genes

```{r time independent, echo=FALSE, message=FALSE, warning=FALSE  }

gostresTop2bi_TI <- gost(query = c(motif3_TI),  
                      organism = "hsapiens",
                      ordered_query = FALSE,
                      domain_scope = "custom",
                      measure_underrepresentation = FALSE,
                      evcodes = FALSE,
                      user_threshold = 0.01,
                      correction_method = c("fdr"),
                      custom_bg = backGL$ENTREZID,
                      sources=c("GO:BP", "KEGG"))
cormotifrespTop2bi_TI <- gostplot(gostresTop2bi_TI, capped = FALSE, interactive = TRUE)
cormotifrespTop2bi_TI


tabletop2Bi_TI <- gostresTop2bi_TI$result %>%
  dplyr::select(c(source, term_id, term_name,intersection_size, term_size, p_value)) 
write.csv(tabletop2Bi_TI,"output/tabletop2Bi_TI.csv")

tabletop2Bi_TI %>% 
  mutate_at(.cols = 6, .funs= scientific_format()) %>% 
  kable(.,) %>% 
  kable_paper("striped", full_width = FALSE) %>%  
  kable_styling(full_width = FALSE, position = "left",bootstrap_options = c("striped","hover")) %>% 
  scroll_box(width = "100%", height = "400px")



  
  
  tabletop2Bi_TI %>% 
    dplyr::filter(source =="GO:BP") %>%
    dplyr::select(p_value,term_name,intersection_size) %>%
    slice_min(., n=13 ,order_by=p_value) %>%
    mutate(log_val = -log10(p_value)) %>%
   # slice_max(., n=10,order_by = p_value) %>%
   ggplot(., aes(x = log_val, y =reorder(term_name,p_value),col=intersection_size)) +
    geom_point(aes(size = intersection_size)) +
    scale_y_discrete(labels = wrap_format(35))+
    guides(col="none", size=guide_legend(title = "# of intersected \n terms"))+
    ggtitle('Time independent response enriched GO:BP terms') +
    xlab("-log 10 (p-value)")+
    #scale_x_continuous(expand = expansion(mult = .2))+
    ylab("GO: BP term")+
     theme_bw()+
 theme(plot.title = element_text(size = rel(1.5), hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.line = element_line(linewidth = 1.5),
        axis.text = element_text(size = 8, color = "black", angle = 0),
        strip.text.x = element_text(size = 15, color = "black", face = "bold"))
  
  
  
  tabletop2Bi_TI %>% 
    dplyr::filter(source =="KEGG") %>% 
    dplyr::select(p_value,term_name,intersection_size) %>%
    slice_min(., n=15 ,order_by=p_value) %>%
    mutate(log_val = -log10(p_value)) %>%
   # slice_max(., n=10,order_by = p_value) %>%
   ggplot(., aes(x = log_val, y =reorder(term_name,p_value),col=intersection_size)) +
    geom_point(aes(size = intersection_size, col="red")) +
  scale_y_discrete(labels = wrap_format(35))+
    guides(col="none", size=guide_legend(title = "# of intersected \n terms"))+
    ggtitle('Time independent response enriched KEGG terms') +
    xlab("-log 10 (p-value)")+
    #scale_x_continuous(expand = expansion(mult = .2))+
    ylab("KEGG term")+
      theme_bw()+
 theme(plot.title = element_text(size = rel(1.5), hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.line = element_line(linewidth = 1.5),
        axis.text = element_text(size = 9, color = "black", angle = 0),
        strip.text.x = element_text(size = 15, color = "black", face = "bold"))


```

###long go frame

```{r all go in one loooooong frame,fig.height=15,fig.width=8}

NR1f <- tableNR %>% dplyr::filter(source=="GO:BP") %>% 
    dplyr::select(p_value,term_name,intersection_size) %>%
    slice_min(., n=10 ,order_by=p_value) %>%
    mutate(log_val = -log10(p_value)) %>%mutate(order_val=rev(as.numeric(rownames(.))))

LR3f <- tabletop2Bi_LR %>% dplyr::filter(source=="GO:BP") %>% 
    dplyr::select(p_value,term_name,intersection_size) %>%
    slice_min(., n=9 ,order_by=p_value) %>%
    mutate(log_val = -log10(p_value))  %>%  mutate(order_val=rev(as.numeric(rownames(.))))


TI3f <- tabletop2Bi_TI %>% 
    dplyr::filter(source =="GO:BP") %>% 
    dplyr::select(p_value,term_name,intersection_size) %>%
    slice_min(., n=10 ,order_by=p_value) %>%
    mutate(log_val = -log10(p_value))  %>% mutate(order_val=rev(as.numeric(rownames(.))))

ER3f <- tabletop2Bi_ER %>% 
    dplyr::filter(source =="GO:BP") %>% 
    dplyr::select(p_value,term_name,intersection_size) %>%
    slice_min(., n=10 ,order_by=p_value) %>%
    mutate(log_val = -log10(p_value))  %>% mutate(order_val=rev(as.numeric(rownames(.))))

GOmotiflong <-list("Early Response"=ER3f,"Late Response"=LR3f,"Time-Independent\nResponse"=TI3f, "No Response"=NR1f)
GOBPlong <- data.table::rbindlist(GOmotiflong, idcol = "motif")
p <- GOBPlong %>% mutate(motif=fct_inorder(motif)) %>% 
  
ggplot(., aes(x = log_val, y=reorder(term_name, order_val, desc=FALSE),col=motif)) +
    geom_point(aes(size = intersection_size, col=motif)) +
  scale_y_discrete(labels = wrap_format(40))+
  facet_grid(motif~., scales = "free_y")+
  
    guides(col=guide_legend(title="Motif group"), size=guide_legend(title = "# of intersected \n terms"))+
    ggtitle('Top 10 enriched GO:BP terms for each motif') +
    xlab("-log 10 (adj. p-value)")+
    #scale_x_continuous(expand = expansion(mult = .2))+
    ylab("GO:BP term")+
      theme_bw()+
 theme(plot.title = element_text(size = rel(1.5), hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.line = element_line(linewidth = 1.5),
        axis.text = element_text(size = 8, color = "black", angle = 0),
        strip.text.x = element_text(size = 15, color = "black", face = "bold"))


#https://stackoverflow.com/questions/41631806/change-facet-label-text-and-background-colour/60046113#60046113
g <- ggplot_gtable(ggplot_build(p))
stripr <- which(grepl('strip-r', g$layout$name))
fills <- c("#F8766D", "#7CAE00", "#00BFC4", "#C77CFF")
k <- 1
for (i in stripr) {
  j <- which(grepl('rect', g$grobs[[i]]$grobs[[1]]$childrenOrder))
  g$grobs[[i]]$grobs[[1]]$children[[j]]$gp$fill <- fills[k]
  k <- k+1
}
#print(grid::grid.draw(g))
grid.draw(g)
#hex <- hue_pal()(4)

#hex
#> hex (red/green/blue/purple default in ggplot)
#[1] "#F8766D" "#7CAE00" "#00BFC4" "#C77CFF"
#p

```

###long go kegg break

```{r kegg break, message=FALSE, warning=FALSE}



LR3fk <- tabletop2Bi_LR %>% dplyr::filter(source=="KEGG") %>% 
    dplyr::select(p_value,term_name,intersection_size) %>%
    slice_min(., n=10 ,order_by=p_value) %>%
    mutate(log_val = -log10(p_value))


TI3fk <- tabletop2Bi_TI %>% 
    dplyr::filter(source =="KEGG") %>% 
    dplyr::select(p_value,term_name,intersection_size) %>%
    slice_min(., n=10 ,order_by=p_value) %>%
    mutate(log_val = -log10(p_value)) 

ER3fk <- tabletop2Bi_ER %>% 
    dplyr::filter(source =="KEGG") %>% 
    dplyr::select(p_value,term_name,intersection_size) %>%
    slice_min(., n=10 ,order_by=p_value) %>%
    mutate(log_val = -log10(p_value)) 

KEGGmotiflong <-list("ER"=ER3fk,"LR"=LR3fk,"TI"=TI3fk)
KEGGlong <- data.table::rbindlist(KEGGmotiflong, idcol = "motif")
KEGGlong %>% group_by(motif) %>% 
ggplot(., aes(x = log_val, y =reorder(term_name,p_value,desc=FALSE),col=motif)) +
    geom_point(aes(size = intersection_size, col=motif)) +
  scale_y_discrete(limits=rev,labels = wrap_format(30))+
    guides(col=guide_legend(title="Motif group"), size=guide_legend(title = "# of intersected \n terms"))+
    ggtitle('Top enriched KEGG terms for each motif') +
    xlab("-log 10 (p-value)")+
    #scale_x_continuous(expand = expansion(mult = .2))+
    ylab("KEGG term")+
      theme_bw()+
 theme(plot.title = element_text(size = rel(1.5), hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.line = element_line(linewidth = 1.5),
        axis.text = element_text(size = 9, color = "black", angle = 0),
        strip.text.x = element_text(size = 15, color = "black", face = "bold"))

```
