---
title: "Figure 8"
author: "ERM"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

```{r packages loading}
library(tidyverse)
library(BiocGenerics)
library(data.table)
library(cowplot)
library(ggsignif)
library(RColorBrewer)
library(broom)

```

```{r data loading, message=FALSE, warning=FALSE, include=FALSE}
toplistall <- readRDS("data/toplistall.RDS")
siglist <- readRDS("data/siglist_final.RDS")
list2env(siglist, envir = .GlobalEnv)
cpmcounts <- readRDS("data/cpmcount.RDS")

my_exp_genes <- read.csv("data/backGL.txt")
GTEx_genes <- read.csv("data/GTEx_gene_list.csv",row.names = 1)
not_eqtls <- read.csv("output/not_eqtls_GTEX.csv",row.names = 1)
heart_gtex <- read.csv("output/heart_gtex.csv",row.names = 1)
egenes <- read.csv("output/egenes.csv",row.names = 1)

```

```{r ggvennoverride function, include=FALSE}

plot_venn <- function (x, show_intersect, set_color, set_size, label, label_geom,
                       label_alpha, label_color, label_size, label_percent_digit,
                       label_txtWidth, edge_lty, edge_size, ...)  {
  venn <- Venn(x)
  data <- process_data(venn)
  p <- ggplot() + geom_sf(aes_string(fill = "count"), data = data@region) +
    geom_sf(aes_string(color = "name"), data = data@setEdge,
            show.legend = F, lty = edge_lty, size = edge_size, color = set_color) +
    geom_sf_text(aes_string(label = "name"), data = data@setLabel,
                 size = set_size, color = set_color) + theme_void()
  if (label != "none" & show_intersect == FALSE) {
    region_label <- data@region %>% dplyr::filter(.data$component ==
                                                    "region") %>% dplyr::mutate(percent = paste(round(.data$count *
                                                                                                        100/sum(.data$count), digits = label_percent_digit),
                                                                                                "%", sep = "")) %>% dplyr::mutate(both = paste(.data$count,
                                                                                                                                               paste0("(", .data$percent, ")"), sep = "\n"))
    if (label_geom == "label") {
      p <- p + geom_sf_label(aes_string(label = label),
                             data = region_label, alpha = label_alpha, color = label_color,
                             size = label_size, lineheight = 0.85, label.size = NA)
    }
    if (label_geom == "text") {
      p <- p + geom_sf_text(aes_string(label = label),
                            data = region_label, alpha = label_alpha, color = label_color,
                            size = label_size, lineheight = 0.85)
    }
  }
  if (show_intersect == TRUE) {
    items <- data@region %>% dplyr::rowwise() %>% dplyr::mutate(text = stringr::str_wrap(paste0(.data$item,
                                                                                                collapse = " "), width = label_txtWidth)) %>% sf::st_as_sf()
    label_coord = sf::st_centroid(items$geometry) %>% sf::st_coordinates()
    p <- ggplot(items) + geom_sf(aes_string(fill = "count")) +
      geom_sf_text(aes_string(label = "name"), data = data@setLabel,
                   inherit.aes = F) + geom_text(aes_string(label = "count",
                                                           text = "text"), x = label_coord[, 1], y = label_coord[,
                                                                                                                 2], show.legend = FALSE) + theme_void()
    ax <- list(showline = FALSE)
    p <- plotly::ggplotly(p, tooltip = c("text")) %>% plotly::layout(xaxis = ax,
                                                                     yaxis = ax)
  }
  p
}

```   




# Figure 8

Dox respose eQTLS are enriched in ACi response genes

## A. 24 hour DEG enrichment in GTEx genes
```{r  GTEx enrich, fig.height=4, fig.width=8}
## create GTEx data set from my data
GTEx <- intersect(GTEx_genes$entrezgene_id,my_exp_genes$ENTREZID)
## exclude GTEX and create nQTL set with other expressed genes
nQTLmy <- my_exp_genes %>%
   dplyr:: filter(!ENTREZID %in%GTEx)
drug_palspc <- c("darkblue","cornflowerblue","darkblue","cornflowerblue")
drug_pal_fact <- c("#8B006D" ,"#DF707E", "#F1B72B" ,"#3386DD", "#707031","#41B333")
#GET nQTL umbers
nQTLsum <- toplistall %>%
  mutate(id =dplyr::case_match(id, "Daunorubicin"~"DNR",
                               "Doxorubicin"~"DOX",
                               "Epirubicin"~"EPI",
                               "Mitoxantrone"~"MTX",
                               "Trastuzumab"~"TRZ",
                               "Vehicle"~"VEH",
                               .default = id)) %>% 
  dplyr::filter(time=="24_hours") %>%
  dplyr::filter(adj.P.Val <0.05) %>%
  mutate(nQTL=if_else(ENTREZID %in% nQTLmy$ENTREZID,'nQTL_y','nQTL_no')) %>% 
  group_by(id,nQTL) %>% 
  tally() %>% 
  separate(nQTL, into=c('set', 'group')) %>% 
  mutate(total=length(nQTLmy$ENTREZID) - n) %>% 
  dplyr::filter(group=="y")
#GETx GTEX numbers
GTExsum <- toplistall %>%
  mutate(id =dplyr::case_match(id, "Daunorubicin"~"DNR",
                               "Doxorubicin"~"DOX",
                               "Epirubicin"~"EPI",
                               "Mitoxantrone"~"MTX",
                               "Trastuzumab"~"TRZ",
                               "Vehicle"~"VEH", 
                               .default = id)) %>% 
  dplyr::filter(time=="24_hours") %>%
  dplyr::filter(adj.P.Val <0.05) %>%
  mutate(GTEx=if_else(ENTREZID %in%GTEx,"GTEx_y","GTEx_no")) %>% 
  group_by(id,GTEx) %>% 
  tally() %>% 
  separate(GTEx, into=c('set', 'group')) %>% 
  mutate(total=length(GTEx) - n) %>% 
  dplyr::filter(group=="y")

##combine and create long data frame for plot
GTEXcr8z <- GTExsum %>% 
  rbind(., nQTLsum) %>% 
  dplyr::select(id,set, n,total) %>%
  mutate(id=factor(id, levels = c('DOX','EPI','DNR','MTX','TRZ','VEH'))) %>%
  pivot_longer(cols=n:total, 
               names_to="group",
               values_to="total") %>%
   mutate(group=factor(group,levels = c("total", "n"),labels=c("not DE","DE"))) %>% 
  mutate(set=factor(set,levels = c("GTEx","nQTL"), labels =c("eGene", "not eGene")))

 
GTEXcr8z %>% 
  ggplot(., aes(x=set,y=total, fill=group))+
  geom_col(position='fill')+
  facet_wrap(~id,nrow=2,ncol=4)+
  theme_classic()+
  scale_fill_manual(values=drug_palspc)+
  ylab("Heart: left ventricle eGenes")+
  xlab("")+
  scale_y_continuous( expand = expansion(c(0, 0.01))) +
  theme(strip.background = element_rect(fill = "white",
                                        linetype=1, 
                                        linewidth = 0.5),
        plot.title = element_text(size=12,
                                  hjust = 0.5,
                                  face="bold"),
        axis.title = element_text(size = 12, 
                                  color = "black"),
        axis.ticks = element_line(linewidth = 1.0),
        axis.text = element_text(color = "black"),
        panel.background = element_rect(colour = "black",
                                        size=1),
        strip.text.x = element_text(size=12,
                                    face = "bold"))#+
  # geom_text(aes(label = Label,   vjust = 1.5, position = position_fill))
ggsave("output/Figures/GTEXenrich.eps",width = 4, height =8, units = "in")
```

## B. 24 hour DEG enrichment in reQTLs
```{r reQTLenrich,fig.height=4, fig.width=8}

knowles4 <-readRDS("output/knowles4.RDS")
knowles5 <-readRDS("output/knowles5.RDS")
Knowles_count <- 
  toplistall %>%
  mutate(id = dplyr::case_match(id, "Daunorubicin"~"DNR",
                                "Doxorubicin"~"DOX",
                                "Epirubicin"~"EPI",
                                "Mitoxantrone"~"MTX",
                                "Trastuzumab"~"TRZ",
                                "Vehicle"~"VEH", 
                                .default = id)) %>%
  filter(id!='TRZ') %>% 
  mutate(id=factor(id, levels = c('DOX','EPI','DNR','MTX','TRZ','VEH'))) %>%
  mutate(time=factor(time, levels=c("3_hours","24_hours"))) %>%
  group_by(time, id) %>%
  mutate(K4 = if_else(ENTREZID %in% knowles4$entrezgene_id,1,0))%>%
  mutate(K5 = if_else(ENTREZID %in% knowles5$entrezgene_id,1,0))%>%
  filter(adj.P.Val<0.05) %>%
  dplyr::summarize(n=n(), K4=sum(K4), K5=sum(K5)) %>% 
  as.tibble() %>% 
  dplyr::select(time,id,K4,K5) %>% 
  rename("K4_y"='K4',"K5_y"='K5') %>% 
  mutate(time = case_match(time, '3_hours'~'3 hrs',
                           '24_hours'~'24 hrs',
                           .default = time)) %>% 
  mutate(K4_n= 417-K4_y, K5_n=273-K5_y) %>% 
  pivot_longer(!c(time,id), 
               names_to='QTL',
               values_to="gene_count") %>%
  separate(QTL,into=c("QTL_type",'group'),sep = '_') %>% 
  mutate(QTL_type =case_match(QTL_type, 
                              'K4'~'base\neGenes',
                              'K5'~'response\neGenes',.default = QTL_type)) %>%
  mutate(time=factor(time, levels=c("3 hrs","24 hrs"))) %>% 
  group_by(id,time,QTL_type) %>% 
  mutate(percent=gene_count/sum(gene_count)*100)  %>% 
  ungroup() %>% 
  filter(time=="24 hrs") %>% 
  mutate(id=factor(id, levels = c('DOX','EPI','DNR','MTX','TRZ','VEH'))) %>%  mutate(group=factor(group, levels= c("n","y"), labels=c("not DE","DE")))
  
  
  ggplot(Knowles_count, aes(x=QTL_type,y=gene_count, group=group,  fill=group))+
    geom_col(position='fill')+
    facet_wrap(~id,nrow=1,ncol=4)+
    theme_classic()+
    ylab("iPSC-CM DOX eGenes ")+
    xlab(" ")+
    scale_color_manual(values=drug_palspc)+
    scale_fill_manual(values=drug_palspc)+
    scale_y_continuous( expand = expansion(c(0, 0.01))) +
    theme(strip.background = element_rect(fill = "white",
                                        linetype=1, 
                                        linewidth = 0.5),
        plot.title = element_text(size=12,
                                  hjust = 0.5,
                                  face="bold"),
        axis.title = element_text(size = 12, 
                                  color = "black"),
        axis.ticks = element_line(linewidth = 1.0),
        axis.text = element_text(color = "black"),
        panel.background = element_rect(colour = "black",
                                        size=1),
        strip.text.x = element_text(size=12,
                                    face = "bold"))

ggsave("output/Figures/knowlesenrich.eps",width = 4, height =8, units = "in")

```


## C. DOXreQTLS strongly overlap other AC drugs
```{r DOXreQTLs across other treatments,fig.height=4, fig.width=8}

r DOXreQTLs de_non de,ffig.height=4, fig.width=8}
DOXreQTLs <- readRDS("output/DOXreQTLs.RDS")
DOXeQTL_table <- toplistall %>% 
  mutate(id = dplyr::case_match(id, "Daunorubicin"~"DNR",
                                "Doxorubicin"~"DOX",
                                "Epirubicin"~"EPI",
                                "Mitoxantrone"~"MTX",
                                "Trastuzumab"~"TRZ",
                                "Vehicle"~"VEH", 
                                .default = id)) %>%
  mutate(sigcount = if_else(adj.P.Val < 0.05,'sig','notsig'))%>%
  mutate(DOXreQTLs=if_else(ENTREZID %in%DOXreQTLs$ENTREZID,"y","no")) %>% 
  dplyr::filter(time =="24_hours") %>% 
  dplyr::select(ENTREZID,id,DOXreQTLs,sigcount) %>%
  group_by(id,DOXreQTLs,sigcount) %>% 
  tally() %>% 
  as.data.frame() %>% 
  filter(DOXreQTLs=="y")

DoxeqtlDEnDE <- DOXeQTL_table %>%
  add_row(id=c("Dox-specific\n DEGs","Dox-specific\n DEGs"),
          DOXreQTLs=c("y"), 
          sigcount=c("notsig","sig"),n = c(62,1)) %>% 
  dplyr::filter(DOXreQTLs=="y") %>% 
  pivot_wider(id, names_from = "sigcount", values_from = "n") %>% 
  mutate(percent= paste0(sprintf("%2.1f", sig/(sig+notsig)*100), "%")) %>% 
  pivot_longer(!c(id,percent), 
               names_to="group", 
               values_to = "count") %>% 
  mutate(id=factor(id, levels=c("EPI","DNR", "MTX","Dox-specific\n DEGs"))) %>% 
  dplyr::filter(id != c("DOX","TRZ")) 
    
    
  ggplot(DoxeqtlDEnDE, aes(y=id,x=count,fill=group))+
  geom_col(position='fill')+
  theme_classic()+
  ylab("")+
  xlab("Proportion of genes")+
  scale_fill_manual(values=c("cornflowerblue","darkred"), 
                    labels=c("not DE","DE"))+
  ggtitle("DOXreQTLs in other treatments")+
  scale_y_discrete(limits=rev)+
  scale_x_continuous(expand = expansion(c(0, 0.05)))+
  geom_text(aes(y=id,x=1, label = percent,hjust =.8))+
  theme(plot.title = element_text( hjust = 0.5),
        axis.title = element_text(size = 16, color = "black"),
        axis.ticks = element_line(linewidth = 1.0),
        axis.line = element_line(linewidth = 1.0),
        axis.text = element_text(size = 12, color = "black", angle = 0),
        strip.text.x = element_text(size = 12, color = "black", face = "bold"))
```

## D. Only one DOXreQTL is associated with Dox-specific DEGs 

```{r DOXreQTLvDOXspeDEG, fig.height=4, fig.width=8}
cpm_boxplot24h <-function(cpmcounts, GOI,brewer_palette, fill_colors, ylab) {
  ##GOI needs to be ENTREZID
  df <- cpmcounts
  df_plot <- df %>% 
      dplyr::filter(rownames(.)==GOI) %>%
      pivot_longer(everything(),
                   names_to = "treatment",
                   values_to = "counts") %>%
      separate(treatment, c("drug","indv","time")) %>%
      mutate(time = case_match(time,"24h"~"24 hours", "3h"~"3 hours")) %>% 
      mutate(indv=factor(indv, levels = c(1,2,3,4,5,6))) %>%
      mutate(drug =case_match(drug, "Da"~"DNR",
                            "Do"~"DOX",
                            "Ep"~"EPI",
                            "Mi"~"MTX",
                            "Tr"~"TRZ",
                            "Ve"~"VEH", .default = drug)) %>% 
      mutate(drug=factor(drug, levels = c('DOX','EPI','DNR','MTX','TRZ','VEH'))) %>% 
      dplyr::filter(time=="24 hours")
    plot <- ggplot2::ggplot(df_plot, aes(x=drug, y=counts))+
      geom_boxplot(position="identity",aes(fill=drug))+
      geom_point(aes(col=indv, size=2, alpha=0.5))+
      guides(alpha= "none", size= "none")+
      scale_color_brewer(palette = brewer_palette, name = "Individual")+
      scale_fill_manual(values=fill_colors)+
      # facet_wrap("time", nrow=1, ncol=2)+
      theme_bw()+
      ylab(ylab)+
      xlab("")+
      ggtitle("24 hours")+
      theme(strip.background = element_rect(fill = "white",linetype=1, linewidth = 0.5),
          plot.title = element_text(size=12,hjust = 0.5,face="bold"),
          axis.title = element_text(size = 10, color = "black"),
          axis.ticks = element_line(linewidth = 1.0),
          panel.background = element_rect(colour = "black", size=1),
          axis.text.x = element_blank(),
          strip.text.x = element_text(margin = margin(2,0,2,0, "pt"),face = "bold"))
    print(plot)
}
cpm_boxplot24h(cpmcounts,GOI='57338',"Dark2",drug_pal_fact,
  ylab=(expression(atop(" ",italic("JPH3")~log[2]~"cpm "))))


```
