---
title: "GO_after_comments"
author: "ERM"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

```{css, echo=FALSE}
pre {
  max-height: 400px;
  overflow-y: auto;
}

pre[class] {
  max-height: 200px;
}
```

```{r  package loading}
library(tidyverse)
library(ggsignif)
library(cowplot)
library(ggpubr)
library(scales)
library(sjmisc)
library(kableExtra)
library(broom)
library(biomaRt)
library(RColorBrewer)
library(gprofiler2)
library(qvalue)
```



```{r data loading}
FC_mine <- readRDS("data/toplistall.RDS")
TRZ_list <- FC_mine %>% 
  filter(id=="TRZ",P.Value < 0.05) #%>% 
backGL <- read_csv("data/backGL.txt", 
    col_types = cols(...1 = col_skip()))

TRZ_list3h <- FC_mine %>% 
  filter(id=="TRZ",P.Value < 0.05, time == "3_hours")
TRZ_list24h <- FC_mine %>% 
  filter(id=="TRZ",P.Value < 0.05, time == "24_hours")

TRZ_listqvalue <- FC_mine %>% 
  filter(id=="TRZ", time=="24_hours") %>% 
  dplyr::select(ENTREZID,P.Value)

qobj <- qvalue(TRZ_listqvalue$P.Value)
hist(qobj)
plot(qobj)

```

### TRZ  nom de (3 & 24 hour)
```{r GOanalysis}
# TRZresgenes <- gost(query = TRZ_list$ENTREZID,
#                     organism = "hsapiens",
#                     significant = FALSE,
#                     ordered_query = TRUE,
#                     domain_scope = "custom",
#                     measure_underrepresentation = FALSE,
#                     evcodes = FALSE,
#                     user_threshold = 0.05,
#                     correction_method = c("fdr"),
#                     custom_bg = backGL$ENTREZID,
#                     sources=c("GO:BP","KEGG"))
# saveRDS(TRZresgenes,"data/DEG-GO/TRZresgenes.RDS")
TRZresgenes <- readRDS("data/DEG-GO/TRZresgenes.RDS")

TRZnom <- gostplot(TRZresgenes, capped = FALSE, interactive = TRUE)
TRZnom

TRZnomtable <- TRZresgenes$result %>% 
  dplyr::select(c(source, term_id,
                  term_name,intersection_size, 
                   term_size, p_value))# %>% 

TRZnomtable %>%
  mutate_at(.vars = 6, .funs = scientific_format()) %>%
  kable(., ) %>%
  kable_paper("striped", full_width = FALSE) %>%
  kable_styling(
    full_width = FALSE,
    position = "left",
    bootstrap_options = c("striped", "hover")
  ) %>%
  scroll_box(width = "100%", height = "400px")

TRZnomtable %>%
  filter(source=="KEGG") %>% 
  mutate_at(.vars = 6, .funs = scientific_format()) %>%
  kable(., caption = "Enrichment of KEGG terms using nominal pvalue TRZ genes in my data") %>%
  kable_paper("striped", full_width = FALSE) %>%
  kable_styling(
    full_width = FALSE,
    position = "left",
    bootstrap_options = c("striped", "hover")
  ) %>%
  scroll_box(width = "100%", height = "400px")


```
### TRZ 3 hour nom de


```{r  TRZ3h}


# TRZresgenes3h <- gost(query = TRZ_list3h$ENTREZID,
#                     organism = "hsapiens",
#                     significant = FALSE,
#                     ordered_query = TRUE,
#                     domain_scope = "custom",
#                     measure_underrepresentation = FALSE,
#                     evcodes = FALSE,
#                     user_threshold = 0.05,
#                     correction_method = c("fdr"),
#                     custom_bg = backGL$ENTREZID,
#                     sources=c("GO:BP","KEGG"))
# saveRDS(TRZresgenes3h,"data/DEG-GO/TRZresgenes3h.RDS")
TRZresgenes3h <- readRDS("data/DEG-GO/TRZresgenes3h.RDS")

TRZnom3h <- gostplot(TRZresgenes3h, capped = FALSE, interactive = TRUE)
TRZnom3h

TRZnomtable3h <- TRZresgenes3h$result %>% 
  dplyr::select(c(source, term_id,
                  term_name,intersection_size, 
                   term_size, p_value))# %>% 

TRZnomtable3h %>%
  mutate_at(.vars = 6, .funs = scientific_format()) %>%
  kable(., ) %>%
  kable_paper("striped", full_width = FALSE) %>%
  kable_styling(
    full_width = FALSE,
    position = "left",
    bootstrap_options = c("striped", "hover")
  ) %>%
  scroll_box(width = "100%", height = "400px")

TRZnomtable3h %>%
  filter(source=="KEGG") %>% 
  mutate_at(.vars = 6, .funs = scientific_format()) %>%
  kable(., caption = "Enrichment of KEGG terms using nominal pvalue TRZ 3hour genes in my data") %>%
  kable_paper("striped", full_width = FALSE) %>%
  kable_styling(
    full_width = FALSE,
    position = "left",
    bootstrap_options = c("striped", "hover")
  ) %>%
  scroll_box(width = "100%", height = "400px")
```


### TRZ 24 hour nom de

```{r TRZ24h}




# TRZresgenes24h <- gost(query = TRZ_list24h$ENTREZID,
#                     organism = "hsapiens",
#                     significant = FALSE,
#                     ordered_query = TRUE,
#                     domain_scope = "custom",
#                     measure_underrepresentation = FALSE,
#                     evcodes = FALSE,
#                     user_threshold = 0.05,
#                     correction_method = c("fdr"),
#                     custom_bg = backGL$ENTREZID,
#                     sources=c("GO:BP","KEGG"))
# saveRDS(TRZresgenes24h,"data/DEG-GO/TRZresgenes24h.RDS")
TRZresgenes24h <- readRDS("data/DEG-GO/TRZresgenes24h.RDS")

TRZnom24h <- gostplot(TRZresgenes24h, capped = FALSE, interactive = TRUE)
TRZnom24h

TRZnomtable24h <- TRZresgenes24h$result %>% 
  dplyr::select(c(source, term_id,
                  term_name,intersection_size, 
                   term_size, p_value))# %>% 

TRZnomtable24h %>%
  mutate_at(.vars = 6, .funs = scientific_format()) %>%
  kable(., ) %>%
  kable_paper("striped", full_width = FALSE) %>%
  kable_styling(
    full_width = FALSE,
    position = "left",
    bootstrap_options = c("striped", "hover")
  ) %>%
  scroll_box(width = "100%", height = "400px")

TRZnomtable24h %>%
  filter(source=="KEGG") %>% 
  mutate_at(.vars = 6, .funs = scientific_format()) %>%
  kable(., caption = "Enrichment of KEGG terms using nominal pvalue TRZ 24hour genes in my data") %>%
  kable_paper("striped", full_width = FALSE) %>%
  kable_styling(
    full_width = FALSE,
    position = "left",
    bootstrap_options = c("striped", "hover")
  ) %>%
  scroll_box(width = "100%", height = "400px")
```

```{r KEGG pathway}
# DAgostres3 <- readRDS("data/DEG-GO/DAgostres3.RDS")
# DAgostres24 <- readRDS("data/DAgostres24.RDS")
# DXgostres <- readRDS("data/DEG-GO/DXgostres.RDS")
# DXgostres24 <- readRDS("data/DEG-GO/DXgostres24.RDS")
# EPgostres <- readRDS("data/DEG-GO/EPgostres.RDS")
# EPgostres24 <- readRDS("data/DEG-GO/EPgostres24.RDS")
# MTgostres <- readRDS("data/DEG-GO/MTgostres.RDS")
# MTgostres24 <- readRDS("data/DEG-GO/MTgostres24.RDS")
# DDEgostres24only <- readRDS("data/DEG-GO/DDEgostres24only.RDS")
# DDEgostres3only <- readRDS("data/DEG-GO/DDEgostres3only.RDS")
# DDEMgostres3 <- readRDS("data/DEG-GO/DDEMgostres3.RDS")
# DDEMgostres24 <- readRDS("data/DEG-GO/DDEMgostres24.RDS")
# TRZresgenes24h  <- readRDS("data/DEG-GO/TRZresgenes24h.RDS") 
# TRZresgenes3h  <- readRDS("data/DEG-GO/TRZresgenes3h.RDS") 
# saveRDS(list3hr,"data/DEG-GO/list3hr.RDS")
# saveRDS(list24hr,"data/DEG-GO/list24hr.RDS")
# list3hr <- list(DAgostres3=DAgostres3,DXgostres=DXgostres,EPgostres=EPgostres,MTgostres=MTgostres,TRZresgenes3h=TRZresgenes3h,DDEgostres3only=DDEgostres3only,DDEMgostres3=DDEMgostres3)
#  list24hr <- list(DAgostres24=DAgostres24,DXgostres24=DXgostres24,EPgostres24=EPgostres24,MTgostres24=MTgostres24,TRZresgenes243h=TRZresgenes24h,DDEgostres24only=DDEgostres24only,DDEMgostres24=DDEMgostres24)

list3hr <- readRDS("data/DEG-GO/list3hr.RDS")
list24hr <- readRDS("data/DEG-GO/list24hr.RDS")
KEGGtrz3 <- c("KEGG:05202", "KEGG:04115", "KEGG:05223", "KEGG:05212","KEGG:05222")
KEGGtrz24 <- c("KEGG:05202", "KEGG:05215", "KEGG:00510")
# testframe <- lapply(list3hr, `[`,'result')

hr3_results <- list3hr |> 
  map(~ .x$result |> dplyr::select(p_value,term_id,term_name,intersection_size))
hr24_results <- list24hr |> 
  map(~ .x$result |> dplyr::select(p_value,term_id,term_name,,intersection_size))

table_3hr <- list_rbind(hr3_results,names_to = "set")%>%
  mutate(log_val = -log10(p_value)) %>% 
  dplyr::filter(term_id %in% KEGGtrz3) %>% 
  mutate(treatment = case_when(set =="DAgostres3"~"DNR",set=="DXgostres" ~ "DOX",set=="EPgostres"~"EPI",set=="MTgostres"~"MTX",set=="TRZresgenes3h"~"TRZ",set=="DDEgostres23only"~"AC",set=="DDEMgostres3"~"TOP2i"))


table_24hr <- list_rbind(hr24_results,names_to = "set") %>%
  mutate(log_val = -log10(p_value))%>% 
  dplyr::filter(term_id %in% KEGGtrz24) %>% 
  mutate(treatment = case_when(set =="DAgostres24"~"DNR",set=="DXgostres24" ~ "DOX",set=="EPgostres24"~"EPI",set=="MTgostres24"~"MTX",set=="TRZresgenes243h"~"TRZ",set=="DDEgostres24only"~"AC",set=="DDEMgostres24"~"TOP2i"))


hr3_results[["TRZresgenes3h"]]  %>% 
    mutate(log_val = -log10(p_value)) %>% 
  dplyr::filter(str_detect(term_id,"^KEGG:")) %>% 
  slice_min(., n=5,order_by=p_value) %>%
    ggplot(., aes(x = log_val, y =reorder(term_name,p_value),col=intersection_size)) +
    geom_point(aes(size = intersection_size)) +
    scale_y_discrete(labels = scales::label_wrap(30))+
  geom_vline(xintercept = (-log10(0.05)), col="red")+
    guides(col="none", size=guide_legend(title = "# of intersected \n terms"))+
    ggtitle('TRZ 3 hour nominal DE\n KEGG pathway enrichment') +
    xlab(expression(" -"~log[10]~("nominal p-value")))+
    ylab("KEGG")+
    theme_bw()+
    theme(plot.title = element_text(size = rel(1.5), hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        # axis.line = element_line(linewidth = 1.5),
        axis.text = element_text(size = 10, color = "black", angle = 0),
        strip.text.x = element_text(size = 12, color = "black", face = "bold"))




hr24_results[["TRZresgenes243h"]]  %>% 
    mutate(log_val = -log10(p_value)) %>% 
  dplyr::filter(str_detect(term_id,"^KEGG:")) %>% 
  slice_min(., n=5,order_by=p_value) %>%
    ggplot(., aes(x = log_val, y =reorder(term_name,p_value), col=intersection_size)) +
    geom_point(aes(size = intersection_size)) +
    scale_y_discrete(labels = scales::label_wrap(30))+
   geom_vline(xintercept = (-log10(0.05)), col="red")+
    guides(col="none", size=guide_legend(title = "# of intersected \n terms"))+
    ggtitle('TRZ 24 hour nominal DE\n KEGG pathway enrichment') +
    xlab(expression(" -"~log[10]~("nominal p-value")))+
    ylab("KEGG")+
    theme_bw()+
    theme(plot.title = element_text(size = rel(1.5), hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        # axis.line = element_line(linewidth = 1.5),
        axis.text = element_text(size = 10, color = "black", angle = 0),
        strip.text.x = element_text(size = 12, color = "black", face = "bold"))
```
```{r GOBP}
hr3_results[["TRZresgenes3h"]]  %>% 
    mutate(log_val = -log10(p_value)) %>% 
  dplyr::filter(str_detect(term_id,"^GO:")) %>% 
  slice_min(., n=5,order_by=p_value) %>%
    ggplot(., aes(x = log_val, y =reorder(term_name,p_value),col=intersection_size)) +
    geom_point(aes(size = intersection_size)) +
    scale_y_discrete(labels = scales::label_wrap(30))+
  geom_vline(xintercept = (-log10(0.05)), col="red")+
    guides(col="none", size=guide_legend(title = "# of intersected \n terms"))+
    ggtitle('TRZ 3 hour nominal DE\n GO:BP enrichment') +
    xlab(expression(" -"~log[10]~("nominal p-value")))+
    ylab("KEGG")+
    theme_bw()+
    theme(plot.title = element_text(size = rel(1.5), hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.line = element_line(linewidth = 1.5),
        axis.text = element_text(size = 10, color = "black", angle = 0),
        strip.text.x = element_text(size = 12, color = "black", face = "bold"))


hr24_results[["TRZresgenes243h"]]  %>% 
    mutate(log_val = -log10(p_value)) %>% 
  dplyr::filter(str_detect(term_id,"^GO:")) %>% 
  slice_min(., n=4,order_by=p_value) %>%
    ggplot(., aes(x = log_val, y =reorder(term_name,p_value), col=intersection_size)) +
    geom_point(aes(size = intersection_size)) +
    scale_y_discrete(labels = scales::label_wrap(30))+
  geom_vline(xintercept = (-log10(0.05)), col="red")+
    guides(col="none", size=guide_legend(title = "# of intersected \n terms"))+
    ggtitle('TRZ 24 hour nominal DE\n GO:BP enrichment') +
    xlab(expression(" -"~log[10]~("nominal p-value")))+
    ylab("KEGG")+
    theme_bw()+
    theme(plot.title = element_text(size = rel(1.5), hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        # axis.line = element_line(linewidth = 1.5),
        axis.text = element_text(size = 10, color = "black", angle = 0),
        strip.text.x = element_text(size = 12, color = "black", face = "bold"))
```



### Link to other pages here:

[Knowles and troponin](https://mward-lab.github.io/Matthews_TOP2i_cardiotox_2023/Knowels_trop_analysis.html)

Other analysis aka after_comments data [here](https://mward-lab.github.io/Matthews_TOP2i_cardiotox_2023/after_comments.html)
