---
title: "After_comments"
author: "ERM"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

```{css, echo=FALSE}
pre {
  max-height: 400px;
  overflow-y: auto;
}

pre[class] {
  max-height: 200px;
}
```




```{r package loading}
library(tidyverse)
library(ggsignif)
library(cowplot)
library(ggpubr)
library(scales)
library(sjmisc)
library(kableExtra)
library(broom)
library(ComplexHeatmap)
library(ggVennDiagram)
library(biomaRt)
library(limma)
library(edgeR)
library(RColorBrewer)

```

```{r eval=FALSE, include=FALSE}
GOI pulling to make data frame
ensembl <- useMart("ensembl", dataset="hsapiens_gene_ensembl")
my_chr <- c(1:22, 'M', 'X', 'Y')  ## creates a filter for each
# #
my_attributes <- c('entrezgene_id', 'ensembl_gene_id', 'hgnc_symbol')

# t
# genehold <- c("ENSG00000049239", "ENSG00000116663","ENSG00000132768",	
# "ENSG00000162601",	
# "ENSG00000142856",	
# "ENSG00000143450",	"ENSG00000165886",	
# "ENSG00000198018",	
# "ENSG00000166881",	
# "ENSG00000100968",	
# "ENSG00000081181",	
# "ENSG00000181827",
# "ENSG00000154945",	
# "ENSG00000125457",	
# "ENSG00000189362",	
# "ENSG00000128274",	
# "ENSG00000104205")

elife.33480.supp14.v2 <- read.delim("~/Ward Lab/Cardiotoxicity/supplementals from papers/elife-33480-supp14-v2.gz")

##had to parse a little differently.  the first table had a shift (the dataframe was downloads incorrectly)
namesof <- read_delim("C:/Users/renee/Downloads/Knowles_raw_data_dryad_download/log2_counts_per_million.txt.gz", delim = "\t", n_max=3)
colnames_k <- colnames(namesof)## This found the first 3 lines of the data and pulled the columnnames into colnames_k
Knowles_log2cpm <- read_table("C:/Users/renee/Downloads/Knowles_raw_data_dryad_download/log2_counts_per_million.txt.gz", col_names = c("ESGN",colnames_k), skip=1) ##this skipped the first row containing the wrong colnames and shifted the data to parse 218 columns)


sample_table_k <- read_delim("C:/Users/renee/Downloads/Knowles_raw_data_dryad_download/sample_table.txt", delim = "\t")

trop_knowles <- read.delim("~/Ward Lab/Cardiotoxicity/supplementals from papers/elife-33480-supp11-v2.txt")
write.csv(trop_knowles, "output/trop_knowles_fun.csv")
write.table(Knowles_log2cpm, "output/Knowles_log2cpm.csv")
saveRDS(Knowles_log2cpm,"data/Knowles_log2cpm_real.RDS")
```


```{r colorpalette}

palette_colors_mine <- colorRampPalette(colors = c("green","white","purple","red" ))(60)
scales::show_col(palette_colors_mine)

```

Here I will attempt to recreate my correlation analysis on the knowles data using their troponin and RNAseq  log2cpm.

```{r troponin knowles}
### genes I want to know about
interest_genes <- read.csv("output/GOI_genelist.txt", row.names = 1)
trop_knowles <- read.csv("output/trop_knowles_fun.csv", row.names = 1)
Knowles_log2cpm <- readRDS("data/Knowles_log2cpm_real.RDS")
trop0.625 <- trop_knowles %>% 
  filter(dosage <1) 
store <- Knowles_log2cpm %>% 
  dplyr::select( 'ESGN',ends_with(c('0.625', '0'))) %>% 
  dplyr::filter(ESGN %in% interest_genes$ensembl_gene_id) %>% 
  pivot_longer(cols=!ESGN, names_to = "ind", values_to = "counts") %>% 
  separate(ind,into=c("cell_line","dosage"), sep = ":") %>%
  mutate(dosage = as.numeric(dosage)) %>% 
  full_join(., trop0.625, by=c("cell_line", "dosage")) %>% 
  group_by(cell_line) %>% 
  full_join(., interest_genes, by = c("ESGN" = "ensembl_gene_id"))
  
  
  ###new graph stuff
  for (gene in interest_genes$ensembl_gene_id){
    gene_plot <- store %>% 
      dplyr::filter(ESGN == gene) %>%
      ggplot(., aes(x=troponin, y=counts))+
      geom_point(aes(col=cell_line))+
      geom_smooth(method="lm")+
      facet_wrap(hgnc_symbol~dosage, scales="free")+
      theme_classic()+
      xlab("troponin I expression") +
      ylab("Gene counts in log2 cpm") +
      ggtitle(expression(paste("Correlation between counts and troponin I Knowles")))+
      scale_color_manual(values = palette_colors_mine, aesthetics = c("color", "fill"))+
     ggpubr:: stat_cor(method="spearman",
                       # cor.coef.name="rho",
               aes(label = paste(..r.label.., ..p.label.., sep = "~`,\n`~")),
               color = "red",
               label.x.npc = 0.01,
               label.y.npc=0.01, 
               size = 3)+
      theme(plot.title = element_text(size = rel(1.5), hjust = 0.5,face = "bold"),
            axis.title = element_text(size = 15, color = "black"),
            axis.ticks = element_line(size = 1.5),
            axis.text = element_text(size = 8, color = "black", angle = 20),
            strip.text.x = element_text(size = 12, color = "black", face = "italic"))
   print(gene_plot)
   
  }



```
Knowles Boxplots of Fig9 genes

```{r KnowBoxfig9}
Knowles_log2cpm_box <- readRDS("data/Knowles_log2cpm_real.RDS")

store_box <- Knowles_log2cpm_box %>% 
  # dplyr::select( 'ESGN',ends_with(c('0.625', '0'))) %>% 
  dplyr::filter(ESGN %in% interest_genes$ensembl_gene_id) %>% 
  pivot_longer(cols=!ESGN, names_to = "ind", values_to = "counts") %>% 
  separate(ind,into=c("cell_line","dosage"), sep = ":") %>%
  mutate(dosage = as.numeric(dosage)) %>% 
  # full_join(., trop0.625, by=c("cell_line", "dosage")) %>% 
  group_by(cell_line) %>% 
  full_join(., interest_genes, by = c("ESGN" = "ensembl_gene_id"))
store_box %>% 
  mutate(dosage=factor(dosage, levels=c('0','0.000', '0.625','1.25', '2.5','5'))) %>% 
  ggplot(., aes(x=dosage,y=counts), group=dosage)+
  geom_boxplot()+
  facet_wrap(~hgnc_symbol)


```




## RNA-seq trial analysis  

### Analysis of expressed genes

```{r data_import_expression}

RNA_seq_trial<- readRDS("data/RNA_seq_trial.RDS")

all_cpmcount <-  read_table("data/Counts_RNA_ERMatthews.txt")
cpm_count_main <- readRDS("data/cpmcount.RDS") %>% rownames_to_column(var = "ENTREZID")
colnames(cpm_count_main) <- colnames(all_cpmcount)


test_run_sample_list <- read.csv("data/test_run_sample_list.txt", row.names = 1)

colnames(RNA_seq_trial) <- c("ENTREZID",test_run_sample_list$Sample_ID)

lcpm_trial <- RNA_seq_trial %>% 
  column_to_rownames("ENTREZID") %>% 
  cpm(., log=TRUE) %>% 
  as.data.frame() #%>% 
 

row_means <- rowMeans(lcpm_trial)
x_trial <- lcpm_trial[row_means > 0,]
dim(x_trial)
list_genes_trial <- rownames(x_trial)
ggVennDiagram::ggVennDiagram(list(list_genes_trial, cpm_count_main$ENTREZID),
                             category.names = c("Trialgenes","Maingenes"),
              show_intersect = TRUE,
              set_color = "black",
              label = "count",
              label_percent_digit = 1,
              label_size = 4,
              label_alpha = 0,
              label_color = "black",
              edge_lty = "solid", set_size = 4.5)#+
  
```





### Correlation of counts files


```{r correlations}

lcpm_trial_full <- RNA_seq_trial %>% 
  column_to_rownames("ENTREZID") %>% 
  cpm(., log=TRUE) %>% 
  as.data.frame() %>% 
  rownames_to_column(var = "ENTREZID")

lcpm_trial_full %>%
  column_to_rownames(var="ENTREZID") %>%
  cor(.) %>% 
  Heatmap(.,layer_fun = function(j, i, x, y, width, height, fill) {
              grid.text(sprintf("%.3f", pindex(., i, j)), x, y, 
            gp = gpar(fontsize = 10))})

lcpm_main <- all_cpmcount %>% 
  column_to_rownames("ENTREZID") %>% 
  cpm(., log=TRUE) %>% 
  as.data.frame() %>% 
  rownames_to_column(var = "ENTREZID") %>% 
  dplyr::select(ENTREZID, all_of(starts_with("DOX"))) %>% 
  dplyr::select(ENTREZID, all_of(ends_with("3h")))  
  
combined_data <- lcpm_main %>%
  full_join(., lcpm_trial_full, by= "ENTREZID") %>% 
  column_to_rownames("ENTREZID") %>% 
  cor(.,) 


  
  Heatmap(combined_data,column_title = "Full gene list",
          layer_fun = function(j, i, x, y, width, height, fill) {
              grid.text(sprintf("%.3f", pindex(combined_data, i, j)), x, y, 
            gp = gpar(fontsize = 10))})
  
  only79_ind <- lcpm_main %>%
  full_join(., lcpm_trial_full, by= "ENTREZID") %>% 
    dplyr::select(ENTREZID,'3hr_0.5',"DOX.4.3h") %>% 
    column_to_rownames("ENTREZID") %>% 
  cor(.,) 

  
  Heatmap(only79_ind,column_title = "Full gene list_79",
          layer_fun = function(j, i, x, y, width, height, fill) {
              grid.text(sprintf("%.3f", pindex(only79_ind, i, j)), x, y, 
            gp = gpar(fontsize = 10))})
  
  
  
lcpm_main_veh <- all_cpmcount %>% 
  column_to_rownames("ENTREZID") %>% 
  cpm(., log=TRUE) %>% 
  as.data.frame() %>% 
  rownames_to_column(var = "ENTREZID") %>% 
  dplyr::select(ENTREZID, all_of(c(starts_with("DOX"),starts_with("VEH")))) %>% 
   dplyr::select(ENTREZID, all_of(ends_with("3h")))  
  

combined_data_veh<- lcpm_main_veh %>%
  full_join(., lcpm_trial_full, by= "ENTREZID") %>% 
  column_to_rownames("ENTREZID") %>% 
  cor(.,) 
  
  
  
  Heatmap(combined_data_veh, column_title = "all genes in list, no filtering",
          layer_fun = function(j, i, x, y, width, height, fill) {
              grid.text(sprintf("%.3f", pindex(combined_data_veh, i, j)), x, y, 
            gp = gpar(fontsize = 8))})
  
  


```

```{r correlation RNAseqtrial filter}

lcpm_trial_filter_main <- lcpm_trial_full %>% 
  filter(ENTREZID %in% cpm_count_main$ENTREZID)
 


lcpm_trial_filter_main %>% 
column_to_rownames(var="ENTREZID") %>%
  cor(.) %>% 
  Heatmap(.,column_title = "Using 14,084 expressed genes from Main data",
          layer_fun = function(j, i, x, y, width, height, fill) {
              grid.text(sprintf("%.3f", pindex(., i, j)), x, y, 
            gp = gpar(fontsize = 8))})


lcpm_trial_filter <- lcpm_trial_full %>% 
  filter(ENTREZID %in% list_genes_trial)
 

lcpm_trial_filter %>% 
column_to_rownames(var="ENTREZID") %>%
  cor(.) %>% 
  Heatmap(.,column_title = "Using 13277 expressed genes",
          layer_fun = function(j, i, x, y, width, height, fill) {
              grid.text(sprintf("%.3f", pindex(., i, j)), x, y, 
            gp = gpar(fontsize = 8))})


lcpm_main_filter_trial <- lcpm_main_veh %>% 
  filter(ENTREZID %in% list_genes_trial)

lcpm_trial_filter %>% 
  full_join(., lcpm_main_filter_trial, by = "ENTREZID") %>% 
  column_to_rownames(var="ENTREZID") %>%
  cor(.) %>% 
  Heatmap(.,column_title = "Using 13277 expressed genes",
          layer_fun = function(j, i, x, y, width, height, fill) {
              grid.text(sprintf("%.3f", pindex(., i, j)), x, y, 
            gp = gpar(fontsize = 8))})


lcpm_trial_filter_main %>% 
  left_join(., lcpm_main, by = "ENTREZID") %>% 
  column_to_rownames(var="ENTREZID") %>%
  dplyr::select(DOX.4.3h,starts_with(("3hr")))%>% 
  cor(.) %>% 
  Heatmap(.,column_title = "Using 14084 expressed genes, just 79-1",
          layer_fun = function(j, i, x, y, width, height, fill) {
              grid.text(sprintf("%.3f", pindex(., i, j)), x, y, 
            gp = gpar(fontsize = 8))})


hr3_indv4 <- lcpm_trial_filter_main %>% 
  left_join(., lcpm_main, by = "ENTREZID") %>% 
  column_to_rownames(var="ENTREZID") %>%
  dplyr::select(DOX.4.3h,`3hr_0.5`,`3hr_0.0`)%>% 
  cor(.) %>% 
  Heatmap(.,column_title = "Using 14084 expressed genes, just 79-1",
          layer_fun = function(j, i, x, y, width, height, fill) {
              grid.text(sprintf("%.3f", pindex(., i, j)), x, y, 
            gp = gpar(fontsize = 8))})
  
plot(hr3_indv4)
 
```
corrlation heatmap of 3hr Dox 1-6 individuals and trial data


```{r ind1-6trial}

lcpm_trial_filter_main %>% 
  left_join(., lcpm_main, by = "ENTREZID") %>% 
  column_to_rownames(var="ENTREZID") %>%
  dplyr::select(starts_with("DOX"),`3hr_0.5`)%>% 
  cor(.) %>% 
  Heatmap(.,column_title = "Using 14084 expressed genes, just 79-1 with all 3 hour samples",
          layer_fun = function(j, i, x, y, width, height, fill) {
              grid.text(sprintf("%.3f", pindex(., i, j)), x, y, 
            gp = gpar(fontsize = 8))})
  #  all3hrdata <- lcpm_main %>%
  # full_join(., lcpm_trial_full, by= "ENTREZID") %>% 
  #   dplyr::select(ENTREZID,'3hr_0.5',start) %>% 
  #   column_to_rownames("ENTREZID") %>% 
  # cor(.,) 




```

### barplots

```{r bar_plots of GOI}


GOI_genelist <- read.csv("output/GOI_genelist.txt")

cpm_boxplot_trial <-function(lcpm_trial, GOI, ylab) {
    ##GOI needs to be ENTREZID
  df_plot <- lcpm_trial %>% 
    dplyr::filter(rownames(.)== GOI) %>%
    pivot_longer(everything(),
                 names_to = "treatment",
                 values_to = "counts") %>%
    separate(treatment, c("time","conc"), sep= "_") %>%
    mutate(conc = factor(conc,levels=c('0.0','0.1','0.5','1.0'), labels = c ("NT", "0.1 uM", "0.5 uM", "1.0 uM")))
  
 plota <-  ggplot2::ggplot(df_plot, aes(x=conc, y= counts))+
    geom_col(position="identity")+
    theme_bw()+
    ylab(ylab)+
    xlab("")+
     ggtitle(paste(GOI))+
      theme(
        # strip.background = element_rect(fill = "white",linetype=1, linewidth = 0.5),
          plot.title = element_text(size=12,hjust = 0.5,face="bold"),
          axis.title = element_text(size = 10, color = "black"),
          axis.ticks = element_line(linewidth = 1.0),
          panel.background = element_rect(colour = "black", size=1),
          # axis.text.x = element_blank(),
          strip.text.x = element_text(margin = margin(2,0,2,0, "pt"),face = "bold"))
    print(plota)
}
  



for (g in seq(1:11)){
  datafilter <- GOI_genelist
  a <- GOI_genelist[g,3]
  # b <- datafilter[g,1]
  cpm_boxplot_trial(lcpm_trial,GOI=datafilter[g,1],
                           ylab =bquote(~italic(.(a))~log[2]~"cpm "))
  
}  


```

expression of trial RNA seq data





