---
title: "LDH_analysis"
author: "ERM"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo= FALSE, warning = FALSE, message = FALSE)
```

##package loading

```{r library loading, message=FALSE, warning=FALSE}

library(readxl)
library(ggpubr)
library(rstatix)
library(tidyverse)
library(zoo)
library(ggplot2)
library(ggsignif)
library(RColorBrewer)
library(stats)
```

## 48 hour Lactate Dehydrogenase results


```{r ldh input at 48 hours, echo=FALSE, message=FALSE, warning=FALSE}

drug_pal <- c("#41B333","#8B006D","#DF707E","#F1B72B", "#3386DD","#707031")

level_order2 <- c('75','87','77','79','78','71')
drug_pal_fact <- c("#8B006D","#DF707E","#F1B72B", "#3386DD","#707031","#41B333")
RINsamplelist <-read_csv("data/RINsamplelist.txt",col_names = TRUE)

via48_full <- read.csv("data/LDH48hoursdata.csv", row.names = 1)
 viability <- via48_full %>% 
  mutate(SampleID=substr(SampleID,4,4)) %>%
  mutate(indv= factor(SampleID, labels= level_order2)) %>%
  mutate(Drug=case_match(Drug,"Daun"~"Daunorubicin",
                         "Doxo"~"Doxorubicin",
                         "Epi"~"Epirubicin",
                         "Mito"~"Mitoxantrone",
                         "Tras"~"Trastuzumab",
                         "Veh"~ "Vehicle", .default= Drug)) %>% 
   mutate(Drug=factor(Drug, levels = c( "Daunorubicin", "Doxorubicin", "Epirubicin", "Mitoxantrone", "Trastuzumab","Vehicle"))) %>%
   dplyr::select(indv,Drug,Conc,Percent) %>%
  group_by(indv,Drug,Conc) %>% summarise(per.live= mean(Percent))
  
norm_LDH <- read.csv("data/norm_LDH.csv",row.names = 1)
norm_LDH48 <- norm_LDH %>% 
  mutate(Drug=case_match(Drug, "Control" ~"Vehicle",.default= Drug)) %>%
  mutate(Drug=factor(Drug, levels = c( "Daunorubicin", "Doxorubicin", "Epirubicin", "Mitoxantrone", "Trastuzumab","Vehicle"))) %>%
  mutate(indv=substring(indv,0,2)) %>%
  mutate(indv= factor(indv,levels= level_order2)) %>% 
  group_by(indv,Drug,Conc) %>% 
  summarise(ldh= mean(norm_val))






ggplot(norm_LDH48, aes(x = as.factor(Conc), y = ldh, group=as.factor(Conc))) +
  geom_boxplot() + 
  geom_point(aes(color= indv, alpha= 0.8))+
  scale_color_brewer(palette = "Dark2",name = "Individual", label = c("1","2","3","4","5","6"))+
  guides(fill = "none", alpha = "none") +
  geom_hline(yintercept = 1,lty =3) +
  theme_bw() +
  ggtitle("Relative lactate release at 48 hours")+
  xlab(expression(paste("Drug [", mu, "M]"))) +
  ylab("Relative lactate release at 48 hours") +
  facet_wrap("Drug") +
  ylim(0, 5)+
  theme(strip.background = element_rect(fill = "transparent")) +
  theme(plot.title = element_text(size = rel(1.5), hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(size = 1.5),
        axis.text = element_text(size = 8, color = "black", angle = 20),
        strip.text.x = element_text(size = 15, color = "black", face = "bold")) 
      
```

### 48 hour viability to LDH activity correlation


```{r 48hour via and ldh}
# ldh_via_48h <-
  viability %>% 
  full_join(., norm_LDH48,by = c("indv","Drug","Conc")) %>% 
  ggplot(., aes(x=per.live, y=ldh))+
  geom_point(aes(col=indv))+
  geom_smooth(method="lm")+
  facet_wrap("Drug", scales="free")+
  theme_classic()+
  xlab("Average viability of cardiomyocytes/100") +
  ylab("Average LDH") +
  ggtitle("Relative viability and relative LDH release at 48 hours")+
  scale_color_brewer(palette = "Dark2",name = "Individual", label = c("1","2","3","4","5","6"))+
  stat_cor(method="pearson",aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")),
           color = "red")+
  theme(plot.title = element_text(size = rel(1.5), hjust = 0.5,face = "bold"),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(size = 1.5),
        axis.text = element_text(size = 8, color = "black", angle = 20),
        strip.text.x = element_text(size = 15, color = "black", face = "bold")) 






```


####24h LDH data frame
```{r ldh 24h results, echo=FALSE, message=FALSE, warning=FALSE}
# ldh24means <- data.frame('',nrow=6)
DA_24_ldh <- matrix(c(1.188,1.222,1.195,1.030,1.074,1.064,1.298,1.282,1.262,
                      1.901,1.975,1.970,3.131,3.246,3.080,1.339,1.438,1.367),
                    ncol =3, nrow =6, byrow =TRUE,
                    dimnames=list(c('87_0.5','79_0.5','75_0.5','77_0.5','78_0.5','71_0.5')))
#ldh24means$Daunorubicin <- rollmean(t(DA_24_ldh),3)
DX_24_ldh <-matrix(c(0.981,0.974,0.978,1.253,1.233,1.292,2.098,2.153,
                     2.114,2.214,2.244,2.239,3.808,3.825,3.735,1.037,1.030,1.030),
                   ncol =3, nrow =6, byrow =TRUE,
                   dimnames=list(c('87_0.5','79_0.5','75_0.5','77_0.5','78_0.5','71_0.5')))
#ldh24means$Doxorubicin <- rollmean(t(DX_24_ldh),3)
EP_24_ldh <-  matrix(c(1.504,1.320,1.469,1.536,1.301,1.531,1.562,1.541,1.558,
                       3.414,3.103,3.236,3.588,3.398,3.611,1.013,0.958,0.991),
                     ncol =3, nrow =6, byrow =TRUE,
                     dimnames=list(c('87_0.5','79_0.5','75_0.5','77_0.5','78_0.5','71_0.5')))
#ldh24means$Epirubicin <- rollmean(t(EP_24_ldh),3)
MT_24_ldh <-  matrix(c(1.508,1.467,1.391,1.493,1.468,1.483,2.010,1.820,1.911,
                       3.089,2.936,2.921,3.623,3.377,3.560,1.222,1.211,1.215),
                     ncol =3, nrow =6, byrow =TRUE,
                     dimnames=list(c('87_0.5','79_0.5','75_0.5','77_0.5','78_0.5','71_0.5')))
#ldh24means$Mitoxantrone <- rollmean(t(MT_24_ldh),3)
TR_24_ldh<-  matrix(c(0.941,0.891,0.953,0.743,0.774,0.812,1.514,1.225,1.252,
                      2.391,1.989,2.172,3.040,2.622,2.613,0.970,0.917,0.895),
                    ncol =3, nrow =6, byrow =TRUE,
                    dimnames=list(c('87_0.5','79_0.5','75_0.5','77_0.5','78_0.5','71_0.5')))
#ldh24means$Trastuzumab <- rollmean(t(TR_24_ldh),3)
VE_24_ldh<-  matrix(c(1.000,1.000,0.977,1.000,1.100,1.096,1.000,0.938,0.951,
                      1.000,1.027,1.038,1.000,1.058,1.062,1.000,1.011,0.975),
                    ncol =3, nrow =6, byrow =TRUE,
                    dimnames=list(c('87_0.5','79_0.5','75_0.5','77_0.5','78_0.5','71_0.5')))
#ldh24means$Vehicle <- rollmean(t(VE_24_ldh),3)
LDH24hstat <- list('VDA'=t.test(VE_24_ldh,DA_24_ldh),
                   'VDX'=t.test(VE_24_ldh,DX_24_ldh),
                   'VEP'=t.test(VE_24_ldh,EP_24_ldh),
                   'VMT'=t.test(VE_24_ldh,MT_24_ldh),
                   'VTR'=t.test(VE_24_ldh,TR_24_ldh),
                   'VVEH'=t.test(VE_24_ldh,VE_24_ldh))

LDH24hstat

```
####24h Tnni data frame

```{r TNNI  using relative to vehicle information}

DA_24_TNNI <- matrix(c(0.790,0.783,1.855,1.693,1.009,1.071,0.736,0.771,
                       1.035,1.202,1.228,1.151),
                    ncol =2, nrow =6, byrow =TRUE,
                    dimnames=list(c('87_0.5','71_0.5','75_0.5','77_0.5','78_0.5','79_0.5')))

DX_24_TNNI <-matrix(c(1.006,1.006,1.295,1.179,1.464,1.493,1.319,1.236,
                      1.231,1.221,1.342,1.296),
                   ncol =2, nrow =6, byrow =TRUE,
                   dimnames=list(c('87_0.5','71_0.5','75_0.5','77_0.5','78_0.5','79_0.5')))

EP_24_TNNI <-  matrix(c(0.955,0.822,1.220,1.092,1.459,1.425,1.076,1.222,
                        1.018,1.269,1.262,1.331),
                     ncol =2, nrow =6, byrow =TRUE,
                     dimnames=list(c('87_0.5','71_0.5','75_0.5','77_0.5','78_0.5','79_0.5')))

MT_24_TNNI <-  matrix(c(1.529,1.682,1.205,1.138,1.436,1.521,1.694,
                        1.778,1.115,1.231,1.006,0.957),
                     ncol =2, nrow =6, byrow =TRUE,
                     dimnames=list(c('87_0.5','71_0.5','75_0.5','77_0.5','78_0.5','79_0.5')))

TR_24_TNNI<-  matrix(c(2.089,1.911,1.245,0.968,1.180,1.168,1.118,
                       1.014,1.496,1.433,1.388,1.235),
                    ncol =2, nrow =6, byrow =TRUE,
                    dimnames=list(c('87_0.5','71_0.5','75_0.5','77_0.5','78_0.5','79_0.5')))

VE_24_TNNI<-  matrix(c(1.000,0.783,1.000,1.000,0.917,1.031,1.000,
                       0.958,1.000,1.000,1.087,1.106),
                    ncol =3, nrow =6, byrow =TRUE,
                    dimnames=list(c('87_0.5','71_0.5','75_0.5','77_0.5','78_0.5','79_0.5')))
tnni24hstat <- list('VDAT'=t.test(VE_24_TNNI,DA_24_TNNI),
                   'VDXT'=t.test(VE_24_TNNI,DX_24_TNNI),
                   'VEPT'=t.test(VE_24_TNNI,EP_24_TNNI),
                   'VMTT'=t.test(VE_24_TNNI,MT_24_TNNI),
                   'VTRT'=t.test(VE_24_TNNI,TR_24_TNNI),
                   'VVEHT'=t.test(VE_24_TNNI,VE_24_TNNI))
tnni24hstat

```
##joint dataframe data

```{r combining ldh and tnni data at 24 hours}

level_order2 <- c('75','87','77','79','78','71')
drug_pal_fact <- c("#8B006D","#DF707E","#F1B72B", "#3386DD","#707031","#41B333")
RINsamplelist <-read_csv("data/RINsamplelist.txt",col_names = TRUE)


mean24ldh <- as.data.frame(rbind(colMeans(t(DA_24_ldh)),
                                 colMeans(t(DX_24_ldh)),
                                 colMeans(t(EP_24_ldh)),
                                 colMeans(t(MT_24_ldh)),
                                 colMeans(t(TR_24_ldh)),
                                 colMeans(t(VE_24_ldh))))
mean24ldh$Drug <- c( "Daunorubicin", "Doxorubicin", "Epirubicin", "Mitoxantrone", "Trastuzumab","Vehicle")  ###add drug name then take out the 0.5 thing
colnames(mean24ldh) <- gsub("_0.5","",colnames(mean24ldh))
##now use pivot longer and join the frames
mean24ldh <-  mean24ldh %>% pivot_longer(.,col=-Drug, names_to = 'indv', values_to = "ldh")



mean24tnni <- as.data.frame(rbind(colMeans(t(DA_24_TNNI)),
                                  colMeans(t(DX_24_TNNI)),
                                  colMeans(t(EP_24_TNNI)),
                                  colMeans(t(MT_24_TNNI)),
                                  colMeans(t(TR_24_TNNI)),
                                  colMeans(t(VE_24_TNNI))))
mean24tnni$Drug <- c( "Daunorubicin", "Doxorubicin", "Epirubicin", "Mitoxantrone", "Trastuzumab","Vehicle")

colnames(mean24tnni) <- gsub("_0.5","",colnames(mean24tnni))
mean24tnni <-  pivot_longer(mean24tnni, 
                            col=-Drug, 
                            names_to = 'indv', 
                            values_to = "tnni")

# ggplot(mean24ldh, aes(x=Drug,y=ldh))+
#   geom_boxplot() +
#   geom_point(aes(col=indv,shape=indv, size =3))+
#   geom_signif(comparisons =list(c("Vehicle","Daunorubicin"),
#                                 c("Vehicle","Doxorubicin"),
#                                 c("Vehicle","Epirubicin"),
#                                 c("Vehicle","Mitoxantrone"),
#                                 c("Vehicle","Trastuzumab")),
#               map_signif_level=FALSE, 
#               textsize =6,
#               tip_length = .1, 
#               vjust = 0.2, step_increase = 0.1)+
#   theme_bw()+
#   ggtitle("Relative LDH release in media")+
#      theme(plot.title = element_text(size = rel(1.5), hjust = 0.5),
#               axis.title = element_text(size = rel(0.8))) 
# 
# 
# ggplot(mean24tnni, aes(x=Drug,y=tnni))+
#   geom_boxplot() +
#   geom_point(aes(col=indv,  size =3))+
#   geom_signif(comparisons =list(c("Control","Daunorubicin"),
#                                 c("Control","Doxorubicin"),
#                                 c("Control","Epirubicin"),
#                                 c("Control","Mitoxantrone"),
#                                 c("Control","Trastuzumab")),
#               map_signif_level=FALSE, 
#               textsize =6,
#               tip_length = .1, 
#               vjust = 0.2, step_increase = 0.1)+
#   theme_bw()+
#   ggtitle("Relative Troponin I release in media")+
#      theme(plot.title = element_text(size = rel(1.5), hjust = 0.5),
#               axis.title = element_text(size = rel(0.8))) 
#   
# 
#  cor(mean24ldh$ldh, mean24tnni$tnni)
# 
# 
tvl24hour <- full_join(mean24ldh,mean24tnni, by=c("Drug","indv"))

# ggplot(tvl24hour, aes(x=ldh,y=tnni))+
#   geom_point(aes(col=indv))+ geom_smooth(method="lm")+
#   facet_wrap("Drug", scales= "free")+theme_bw()+
#   stat_cor(aes(label = after_stat(rr.label)), color = "red", geom = "label")+
#   ggtitle("ldh verses cTNNI 24 hour by Drug")


```


##  RNA normalized 24 hour cTNNI / LDH

```{r correlation}

level_order2 <- c('75','87','77','79','78','71')
drug_pal_fact <- c("#8B006D","#DF707E","#F1B72B", "#3386DD","#707031","#41B333")


RINsamplelist <- read_csv("data/RINsamplelist.txt")

RNAnormlist <- RINsamplelist %>% 
  mutate(Drug=case_match(Drug,"daunorubicin"~"Daunorubicin",
                         "doxorubicin"~"Doxorubicin",
                         "epirubicin"~"Epirubicin",
                         "mitoxantrone"~"Mitoxantrone",
                         "trastuzumab"~"Trastuzumab",
                         "vehicle"~"Vehicle", .default= Drug)) %>%
  filter(time =="24h") %>%
  ungroup() %>%
  dplyr::select(indv,Drug,Conc_ng.ul) %>%
  mutate(indv= factor(indv,levels= level_order2))


RNAnormlist <- RNAnormlist %>%
  full_join(.,tvl24hour,by= c("Drug", "indv")) %>%
  mutate(rldh= ldh/Conc_ng.ul) %>%
  mutate(rtnni=tnni/Conc_ng.ul)

write.csv(RNAnormlist,"output/TNNI_LDH_RNAnormlist.txt")


ggplot(RNAnormlist, aes(x=rldh, y=rtnni))+
  geom_point(aes(col=indv))+
  geom_smooth(method="lm")+
  stat_cor(method="pearson",  
           label.x.npc = 0, 
           label.y.npc = 1,  
           aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")),
           color = "red")+
  facet_wrap("Drug", scales="free")+
  scale_color_brewer(palette = "Dark2")+
  scale_color_brewer(palette = "Dark2",name = "Individual", label = c("1","2","3","4","5","6"))+
  
  ylab("Troponin I release at 24 hours")+
  xlab("Lactate DH release at 24 hours")+
  theme_classic()+
  theme(strip.background = element_rect(fill = "transparent")) +
  theme(plot.title = element_text(size = rel(1.5), hjust = 0.5),
        legend.position = "none",
         axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.line = element_line(linewidth = 1.5),
        axis.text = element_text(size = 12, color = "black", angle = 0),
        strip.text.x = element_text(size = 15, color = "black", face = "bold"))+
  ggtitle("Correlation between Troponin I release and LDH activity")

RNAnormlist %>% 
  mutate(Drug = factor(Drug, levels = c("Vehicle",
                                        "Daunorubicin",                                                                      "Doxorubicin",
                                        "Epirubicin",
                                        "Mitoxantrone",
                                        "Trastuzumab"))) %>%
  ggplot(., aes(x=Drug, y=rldh))+
  geom_boxplot(position = "identity", fill = drug_pal)+
  geom_point(aes(col=indv, size =3,alpha=0.5))+
  geom_signif(comparisons =list(c("Vehicle","Daunorubicin"),
                                c("Vehicle","Doxorubicin"),
                                c("Vehicle","Epirubicin"),
                                c("Vehicle","Mitoxantrone"),
                                c("Vehicle","Trastuzumab")),
              test="t.test",
              map_signif_level=TRUE,
              textsize =4,
              step_increase = 0.1)+
  theme_classic()+
  guides(size = "none",alpha="none")+
  scale_color_brewer(palette = "Dark2", name = "Individual")+
  xlab("")+
  ylab("Relative LDH activity ")+
  ggtitle("Lactate dehydrogenase release at 24 hours")+
  theme_classic()+
  theme(strip.background = element_rect(fill = "transparent")) +
  theme(plot.title = element_text(size = rel(1.5), hjust = 0.5),
        legend.position = "none",
         axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.line = element_line(linewidth = 1.5),
        axis.text = element_text(size = 12, color = "black", angle = 0),
        strip.text.x = element_text(size = 15, color = "black", face = "bold"))


RNAnormlist %>% 
  mutate(Drug = factor(Drug, levels = c("Vehicle",
                                        "Daunorubicin",                                                                      "Doxorubicin",
                                        "Epirubicin",
                                        "Mitoxantrone",
                                        "Trastuzumab"))) %>%
  ggplot(., aes(x=Drug, y=rtnni))+
  geom_boxplot(position = "identity", fill = drug_pal)+
  geom_point(aes(col=indv, size =3,alpha=0.5))+
  geom_signif(comparisons =list(c("Vehicle","Daunorubicin"),
                                c("Vehicle","Doxorubicin"),
                                c("Vehicle","Epirubicin"),
                                c("Vehicle","Mitoxantrone"),
                                c("Vehicle","Trastuzumab")),
              test="t.test",
              map_signif_level=TRUE,
              textsize =4,
              step_increase = 0.1)+
  theme_classic()+
  guides(size = "none",alpha="none")+
  scale_color_brewer(palette = "Dark2", name = "Individual")+
  xlab("")+
  ylab("Relative Troponin I levels ")+
  ggtitle("Troponin I release at 24 hours")+
  theme_classic()+
  theme(strip.background = element_rect(fill = "transparent")) +
  theme(plot.title = element_text(size = rel(1.5), hjust = 0.5),
        legend.position = "none",
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.line = element_line(linewidth = 1.5),
        axis.text = element_text(size = 12, color = "black", angle = 0),
        strip.text.x = element_text(size = 15, color = "black", face = "bold"))



```


## Calcium data at 24 hours


```{r calcium addition}
library(tidyverse)
library(ggsignif)
library(readr)
library(ggalt)

clamp_summary <- read.csv("data/Clamp_Summary.csv", row.names=1)

level_order2 <- c('75','87','77','79','78','71')
calcium_data <- read_csv("data/DF_Plate_Peak.csv", col_types = cols(...1 = col_skip()))

drug_palexpand <- c("#41B333","#8B006D","#DF707E","#F1B72B", "#3386DD","#707031","purple3","darkgreen", "darkblue")
#named colors: dark pink,Red,yellow,blue, dark grey, green(green is always control, may need to move pal around)



```

### Beat Rate
```{r beat  rate plot}


calcium_data %>% rename('Treatment'='Condition') %>%
  rename('indv'='Experiment') %>%
  mutate(Drug =case_match(Treatment, "Dau_0.5"~"Daunorubicin",  "Dau_1" ~"Daunorubicin",
                          "Dox_0.5"~"Doxorubicin",  "Dox_1" ~"Doxorubicin",
                          "Epi_0.5"~"Epirubicin",  "Epi_1" ~"Epirubicin",
                          "Mito_0.5"~"Mitoxantrone","Mito_1"~"Mitoxantrone",
                          "Tras_0.5"~"Trastuzumab", "Tras_1"~"Trastuzumab","Control" ~"Vehicle", .default = Treatment)) %>%
  mutate(Drug=factor(Drug, levels = c("Vehicle", "Daunorubicin", "Doxorubicin","Epirubicin","Mitoxantrone","Trastuzumab"))) %>%
  mutate(Conc =case_match(Treatment, "Dau_0.5"~"0.5",  "Dau_1" ~"1.0",
                          "Dox_0.5"~"0.5",  "Dox_1" ~"1.0",
                          "Epi_0.5"~"0.5",  "Epi_1" ~"1.0",
                          "Mito_0.5"~"0.5","Mito_1"~"1.0",
                          "Tras_0.5"~"0.5", "Tras_1"~"1.0",'Control'~'0', .default = Treatment)) %>%
  dplyr::select(Drug,Conc,indv,Rate) %>%#Peak_variance,Ave_FF0,
  mutate(indv=substr(indv,1,2)) %>%
  mutate(indv=factor(indv, levels = level_order2)) %>%

  mutate(contrl= 0.383) %>%
  mutate(norm_rate=Rate/contrl) %>%
  filter(Conc==0| Conc==0.5) %>%
  ggplot(., aes(x=Drug, y=Rate))+
  geom_boxplot(position = "identity", fill= drug_pal)+
  geom_point(aes(col=indv, size=2, alpha=0.5))+
  guides(alpha= "none")+
  geom_signif(comparisons = list(c("Daunorubicin", "Vehicle"),
                                 c("Doxorubicin", "Vehicle"),
                                 c("Epirubicin", "Vehicle"),
                                 c("Mitoxantrone", "Vehicle"),
                                 c("Trastuzumab","Vehicle")),
              test = "t.test",
              map_signif_level = TRUE,
              step_increase = 0.1,
              textsize = 4)+
  guides(alpha= "none",size="none")+
  scale_color_brewer(palette = "Dark2", name = "Individual",label=c("2","3","5"))+
  ggtitle("Contraction rate")+
  theme_classic()+
  guides(size = "none",colour = guide_legend(override.aes = list(size=4, alpha= 0.5)))+
  labs(y = "avg. beats/sec")+
  theme(plot.title = element_text(size=18,hjust = 0.5),
    axis.title = element_text(size = 15, color = "black"),
    axis.ticks = element_line(linewidth = 1.5),
    axis.line = element_line(linewidth = 1.5),
    axis.text = element_text(size = 12, color = "black", angle = 0),
    strip.text.x = element_text(size = 15, color = "black", face = "bold"))

```


### Mean amplitude

```{r Mean Amplitude}


clamp_summary %>%
  rename('Treatment'='Cond') %>%
  rename('indv'='Exp') %>%
  mutate(Drug =case_match(Treatment, "Dau_0.5"~"Daunorubicin",  "Dau_1" ~"Daunorubicin",
                          "Dox_0.5"~"Doxorubicin",  "Dox_1" ~"Doxorubicin",
                          "Epi_0.5"~"Epirubicin",  "Epi_1" ~"Epirubicin",
                          "Mito_0.5"~"Mitoxantrone","Mito_1"~"Mitoxantrone",
                          "Tras_0.5"~"Trastuzumab", "Tras_1"~"Trastuzumab",
                          "Control" ~"Vehicle" ,.default = Treatment)) %>%
  mutate(Drug=factor(Drug, levels = c("Vehicle", 
                                      "Daunorubicin",
                                      "Doxorubicin",
                                      "Epirubicin",
                                      "Mitoxantrone",
                                      "Trastuzumab"))) %>%
  mutate(Conc =case_match(Treatment, "Dau_0.5"~"0.5",  "Dau_1" ~"1.0",
                          "Dox_0.5"~"0.5",  "Dox_1" ~"1.0",
                          "Epi_0.5"~"0.5",  "Epi_1" ~"1.0",
                          "Mito_0.5"~"0.5","Mito_1"~"1.0",
                          "Tras_0.5"~"0.5", "Tras_1"~"1.0",'Control'~'0', .default = Treatment)) %>%
  rename(c('Mean_Amplitude'='R1S1_Mean..a.u..',
           'Rise_Slope'='R1S1_Rise_Slope..a.u..ms.',
           'FWHM'='R1S1_Half_Width..ms.',
           'Decay_Slope'='R1S1_Decay_Slope..a.u..ms.',
           'Decay_Time'='Decay_Time..ms.',
           'Rise_Time'='R1S1_Rise_Time')) %>%
  mutate(indv=substr(indv,1,2)) %>%
  mutate(indv=factor(indv, levels = level_order2)) %>%
  filter(Conc==0| Conc==0.5) %>%
  dplyr::select(Drug,Conc,indv,Mean_Amplitude,FWHM,Rise_Slope,Decay_Slope) %>%
  ggplot(.,aes(Drug,Mean_Amplitude))+
  geom_boxplot(position = "identity", fill= drug_pal)+
  geom_point(aes(col=indv, size=2, alpha=0.5))+
  guides(alpha= "none",size="none")+
  scale_color_brewer(palette = "Dark2", name = "Individual",label=c("2","3","5"))+
  geom_signif(comparisons = list(c("Daunorubicin", "Vehicle"),
                                 c("Doxorubicin", "Vehicle"),
                                 c("Epirubicin", "Vehicle"),
                                 c("Mitoxantrone", "Vehicle"),
                                 c("Trastuzumab","Vehicle")),
              test = "t.test",
              map_signif_level = TRUE,
              step_increase = 0.1,
              textsize = 4)+
  labs(y = "a.u.")+
  ggtitle("Mean amplitude")+
  theme_classic()+
  theme(plot.title = element_text(size=18,hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.line = element_line(linewidth = 1.5),
        axis.text = element_text(size = 12, color = "black", angle = 0),
        strip.text.x = element_text(size = 15, color = "black", face = "bold"))


```



### Full-Width-half max

```{r FWHM}



clamp_summary %>%
  rename('Treatment'='Cond') %>%
  rename('indv'='Exp') %>%
  mutate(Drug =case_match(Treatment, "Dau_0.5"~"Daunorubicin",  "Dau_1" ~"Daunorubicin",
                          "Dox_0.5"~"Doxorubicin",  "Dox_1" ~"Doxorubicin",
                          "Epi_0.5"~"Epirubicin",  "Epi_1" ~"Epirubicin",
                          "Mito_0.5"~"Mitoxantrone","Mito_1"~"Mitoxantrone",
                          "Tras_0.5"~"Trastuzumab", "Tras_1"~"Trastuzumab","Control" ~"Vehicle" ,.default = Treatment)) %>%
  mutate(Drug=factor(Drug, levels = c("Vehicle", "Daunorubicin", "Doxorubicin","Epirubicin","Mitoxantrone","Trastuzumab"))) %>%
  mutate(Conc =case_match(Treatment, "Dau_0.5"~"0.5",  "Dau_1" ~"1.0",
                          "Dox_0.5"~"0.5",  "Dox_1" ~"1.0",
                          "Epi_0.5"~"0.5",  "Epi_1" ~"1.0",
                          "Mito_0.5"~"0.5","Mito_1"~"1.0",
                          "Tras_0.5"~"0.5", "Tras_1"~"1.0",'Control'~'0', .default = Treatment)) %>%
  rename(c('Mean_Amplitude'='R1S1_Mean..a.u..',
           'Rise_Slope'='R1S1_Rise_Slope..a.u..ms.',
           'FWHM'='R1S1_Half_Width..ms.',
           'Decay_Slope'='R1S1_Decay_Slope..a.u..ms.',
           'Decay_Time'='Decay_Time..ms.',
           'Rise_Time'='R1S1_Rise_Time')) %>%
  mutate(indv=substr(indv,1,2)) %>%
  mutate(indv=factor(indv, levels = level_order2)) %>%
  filter(Conc==0| Conc==0.5) %>%
  dplyr::select(Drug,Conc,indv,Mean_Amplitude,FWHM,Rise_Slope,Decay_Slope) %>%
  ggplot(.,aes(Drug,FWHM))+
  geom_boxplot(position = "identity", fill= drug_pal)+
  geom_point(aes(col=indv, size=2, alpha=0.5))+
  guides(alpha= "none",size="none")+
  scale_color_brewer(palette = "Dark2", name = "Individual",label=c("2","3","5"))+
  geom_signif(comparisons = list(c("Daunorubicin", "Vehicle"),
                                 c("Doxorubicin", "Vehicle"),
                                 c("Epirubicin", "Vehicle"),
                                 c("Mitoxantrone", "Vehicle"),
                                 c("Trastuzumab","Vehicle")),
              test = "t.test",
              map_signif_level = TRUE,
              step_increase = 0.1,
              textsize = 4)+
  ggtitle(expression(paste("Full-width at half-max")))+
  theme_bw()+
  guides(size = "none")+
  labs(y = "a.u.")+
  theme_classic()+
  theme(plot.title = element_text(size=18,hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.line = element_line(linewidth = 1.5),
        axis.text = element_text(size = 12, color = "black", angle = 0),
        strip.text.x = element_text(size = 15, color = "black", face = "bold"))




```



### Rising Slope

```{r rising slope}

clamp_summary %>%
  rename('Treatment'='Cond') %>%
  rename('indv'='Exp') %>%
  mutate(Drug =case_match(Treatment, "Dau_0.5"~"Daunorubicin",  
                          "Dau_1" ~"Daunorubicin",
                          "Dox_0.5"~"Doxorubicin",  
                          "Dox_1" ~"Doxorubicin",
                          "Epi_0.5"~"Epirubicin",  
                          "Epi_1" ~"Epirubicin",
                          "Mito_0.5"~"Mitoxantrone","Mito_1"~"Mitoxantrone",
                          "Tras_0.5"~"Trastuzumab", "Tras_1"~"Trastuzumab",
                          "Control" ~"Vehicle" ,.default = Treatment)) %>%
  mutate(Drug=factor(Drug, levels = c("Vehicle", "Daunorubicin",
                                      "Doxorubicin","Epirubicin","Mitoxantrone","Trastuzumab"))) %>%
  mutate(Conc =case_match(Treatment, "Dau_0.5"~"0.5",  "Dau_1" ~"1.0",
                          "Dox_0.5"~"0.5",  "Dox_1" ~"1.0",
                          "Epi_0.5"~"0.5",  "Epi_1" ~"1.0",
                          "Mito_0.5"~"0.5","Mito_1"~"1.0",
                          "Tras_0.5"~"0.5", "Tras_1"~"1.0",'Control'~'0', .default = Treatment)) %>%
  rename(c('Mean_Amplitude'='R1S1_Mean..a.u..',
           'Rise_Slope'='R1S1_Rise_Slope..a.u..ms.',
           'FWHM'='R1S1_Half_Width..ms.',
           'Decay_Slope'='R1S1_Decay_Slope..a.u..ms.',
           'Decay_Time'='Decay_Time..ms.',
           'Rise_Time'='R1S1_Rise_Time')) %>%
  mutate(indv=substr(indv,1,2)) %>%
  mutate(indv=factor(indv, levels = level_order2)) %>%
  filter(Conc==0| Conc==0.5) %>%
  dplyr::select(Drug,Conc,indv,Mean_Amplitude,FWHM,Rise_Slope,Decay_Slope) %>%
  ggplot(.,aes(Drug,Rise_Slope))+
  geom_boxplot(position = "identity", fill= drug_pal)+
  geom_point(aes(col=indv, size=2, alpha=0.5))+
  guides(alpha="none", indv = "none", size = "none")+
   scale_color_brewer(palette = "Dark2", name = "Individual",label=c("2","3","5"))+
  geom_signif(comparisons = list(c("Daunorubicin", "Vehicle"),
                                 c("Doxorubicin", "Vehicle"),
                                 c("Epirubicin", "Vehicle"),
                                 c("Mitoxantrone", "Vehicle"),
                                 c("Trastuzumab","Vehicle")),
              test = "t.test",
              map_signif_level = TRUE,
              step_increase = 0.1,
              textsize = 4)+
  ggtitle(expression(paste("Rising slope")))+
  labs(y = "a.u./sec")+
  theme_classic()+
  theme(plot.title = element_text(size=18,hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.line = element_line(linewidth = 1.5),
        axis.text = element_text(size = 12, color = "black", angle = 0),
        strip.text.x = element_text(size = 15, color = "black", face = "bold"))




```



### Decay slope

```{r Decay slope}
clamp_summary %>%
  rename('Treatment'='Cond') %>%
  rename('indv'='Exp') %>%
  mutate(Drug =case_match(Treatment, "Dau_0.5"~"Daunorubicin",  "Dau_1" ~"Daunorubicin",
                          "Dox_0.5"~"Doxorubicin",  "Dox_1" ~"Doxorubicin",
                          "Epi_0.5"~"Epirubicin",  "Epi_1" ~"Epirubicin",
                          "Mito_0.5"~"Mitoxantrone","Mito_1"~"Mitoxantrone",
                          "Tras_0.5"~"Trastuzumab", "Tras_1"~"Trastuzumab","Control" ~"Vehicle" ,.default = Treatment)) %>%
  mutate(Drug=factor(Drug, levels = c("Vehicle", "Daunorubicin", "Doxorubicin","Epirubicin","Mitoxantrone","Trastuzumab"))) %>%
  mutate(Conc =case_match(Treatment, "Dau_0.5"~"0.5",  "Dau_1" ~"1.0",
                          "Dox_0.5"~"0.5",  "Dox_1" ~"1.0",
                          "Epi_0.5"~"0.5",  "Epi_1" ~"1.0",
                          "Mito_0.5"~"0.5","Mito_1"~"1.0",
                          "Tras_0.5"~"0.5", "Tras_1"~"1.0",'Control'~'0', .default = Treatment)) %>%
  rename(c('Mean_Amplitude'='R1S1_Mean..a.u..',
           'Rise_Slope'='R1S1_Rise_Slope..a.u..ms.',
           'FWHM'='R1S1_Half_Width..ms.',
           'Decay_Slope'='R1S1_Decay_Slope..a.u..ms.',
           'Decay_Time'='Decay_Time..ms.',
           'Rise_Time'='R1S1_Rise_Time')) %>%
  mutate(indv=substr(indv,1,2)) %>%
  mutate(indv=factor(indv, levels = level_order2)) %>%
  filter(Conc==0| Conc==0.5) %>%
  dplyr::select(Drug,Conc,indv,Mean_Amplitude,FWHM,Rise_Slope,Decay_Slope) %>%
  ggplot(.,aes(Drug,Decay_Slope))+
  geom_boxplot(position = "identity", fill= drug_pal)+
  geom_point(aes(col=indv, size=2, alpha=0.5))+
  guides(alpha="none", indv = "none", size = "none")+
   scale_color_brewer(palette = "Dark2", name = "Individual",label=c("2","3","5"))+
  geom_signif(comparisons = list(c("Daunorubicin", "Vehicle"),
                                 c("Doxorubicin", "Vehicle"),
                                 c("Epirubicin", "Vehicle"),
                                 c("Mitoxantrone", "Vehicle"),
                                 c("Trastuzumab","Vehicle")),
              test = "t.test",
              map_signif_level = TRUE,
              step_increase = 0.1,
              textsize = 4)+
  ggtitle(expression(paste("Decay slope ")))+
  labs(y = "a.u.")+
  theme_classic()+
  theme(plot.title = element_text(size=18,hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.line = element_line(linewidth = 1.5),
        axis.text = element_text(size = 12, color = "black", angle = 0),
        strip.text.x = element_text(size = 15, color = "black", face = "bold"))

```

### k means plot
```{r kmeans code}



k_means <- read.csv("data/K_cluster_kisthree.csv")

# k_means %>% mutate(Drug =case_match(Drug_Name, "Dau_0.5"~"Daunorubicin",  
#                                     "Dau_0.5.1" ~"Daunorubicin",
#                                     "Dau_0.5.2" ~"Daunorubicin",
#                                     "Dox_0.5"~"Doxorubicin",  
#                                     "Dox_0.5.1" ~"Doxorubicin",
#                                     "Dox_0.5.2" ~"Doxorubicin",
#                                     "Epi_0.5"~"Epirubicin", 
#                                     "Epi_0.5.1"~"Epirubicin",
#                                     "Epi_0.5.2" ~ "Epirubicin",
#                                     "Mito_0.5" ~ "Mitoxantrone", 
#                                     "Mito_0.5.1" ~"Mitoxantrone", 
#                                     "Mito_0.5.2" ~ "Mitoxantrone",
#                                     "Tras_0.5" ~ "Trastuzumab", 
#                                     "Tras_0.5.1" ~"Trastuzumab", 
#                                     "Tras_0.5.2" ~ "Trastuzumab",
#                                     "Control.1" ~ "Vehicle", 
#                                     "Control.2" ~  "Vehicle", 
#                                     "Control" ~ "Vehicle", .default = Drug_Name)) %>%
#   ggplot(., aes(x = PC1,y = PC2,col = factor(Cluster),shape = Cluster)) +
#   geom_point(size = 5) +
#   scale_color_manual(values = c("purple3", "darkgreen", "darkblue"))


k_means %>% mutate(Drug =case_match(Drug_Name, "Dau_0.5"~"Daunorubicin",
                                    "Dau_0.5.1" ~"Daunorubicin",
                                    "Dau_0.5.2" ~"Daunorubicin",
                                    "Dox_0.5"~"Doxorubicin",  
                                    "Dox_0.5.1" ~"Doxorubicin",
                                    "Dox_0.5.2" ~"Doxorubicin",
                                    "Epi_0.5"~"Epirubicin",
                                    "Epi_0.5.1"~"Epirubicin",
                                    "Epi_0.5.2"~"Epirubicin",
                                    "Mito_0.5"~"Mitoxantrone",
                                    "Mito_0.5.1"~"Mitoxantrone",
                                    "Mito_0.5.2"~"Mitoxantrone",
                                    "Tras_0.5"~"Trastuzumab", 
                                    "Tras_0.5.1"~"Trastuzumab", 
                                    "Tras_0.5.2"~"Trastuzumab",
                                    "Control.1"~"Vehicle",
                                    "Control.2"~"Vehicle",
                                    "Control"~"Vehicle",.default = Drug_Name)) %>%
  mutate(Drug=factor(Drug, levels = c("Vehicle", 
                                      "Daunorubicin",
                                      "Doxorubicin",
                                      "Epirubicin",
                                      "Mitoxantrone",
                                      "Trastuzumab"))) %>%
  mutate(Cluster=factor(Cluster)) %>%
  ggplot(., aes(x=PC1, y=PC2, col= Drug))+
  geom_point(shape = 17,size=7)+
  scale_color_manual(values=drug_pal)+
  geom_encircle(aes(group=Cluster))+
  annotate("text", label = c("Cluster 1","Cluster 2", "Cluster 3"), x = c(-2,0,1.5),y=c(-0.5,0,0.5))+
  ggtitle(expression("PCA of Ca"^"2+"~"data with K-means clustering"))+
  theme_bw()+
  labs(x = "PC 1 (54 %)",y = "PC 2 (34%)")+
  theme(plot.title=element_text(size= 14,hjust = 0.5),
        axis.title = element_text(size = 10, color = "black"),
        axis.ticks = element_line(size = 1.5),
        axis.text = element_text(size = 12, color = "black", angle = 0),
        strip.text.x = element_text(size = 15, color = "black", face = "bold"))
```

