---
title: "Highly variable genes"
author: "ERM"
date: "`r Sys.Date()`"
output: 
  html_document: 
    fig_height: 6
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

Goals for this page:


  I will examine the AC-shared variable genes within AC-shared response genes 

```{r packages loading}
library(tidyverse)
library(VennDiagram)
library(paletteer)
library(ggVennDiagram)
library(gridtext)
library(scales)
library(kableExtra)
library(ComplexHeatmap)
library(data.table)


# library(tidyverse)
library(ggpubr)
library(ggsignif)

# library(paletteer)
# library(ggVennDiagram)
# library(gridtext)
# library(scales)
# library(kableExtra)
library(qvalue)
# library(data.table)
# library(ComplexHeatmap)
```


```{r data set loading}

drug_palc <- c("#8B006D","#DF707E","#F1B72B", "#3386DD","#707031","#41B333")
Vargenes <- readRDS("data/geneset_24.RDS")
expressedgenes <- read.csv("data/backGL.txt")
venn24part <- VennDiagram::get.venn.partitions(Vargenes)
backGL <- read.csv("data/backGL.txt", row.names = 1)


toplistall <- readRDS("data/toplistall.RDS")
  #get sig files made with 0.05 data this way(data created on run)
siglist <- readRDS("data/siglist_final.RDS")


siglist24 <- siglist[6:9]
test <- siglist24[1]["ENTREZID"]
sig_24_ENTREZID <- sapply(siglist24,"[[",1)
sig_24_venn<- VennDiagram::get.venn.partitions(sig_24_ENTREZID)




```



## AC shared
```{r enrichment checks}

AC_share_var <- venn24part$..values..[[25]] #203
not_AC_shared <- setdiff(expressedgenes$ENTREZID,AC_share_var)
AC_shared_sig <- sig_24_venn$..values..[[9]] ##4435
length(intersect(AC_share_var,AC_shared_sig))  #(88 overlap)
length(intersect(not_AC_shared,AC_shared_sig)) #4347
# 
# stored <-
  expressedgenes %>% 
  mutate(var_AC= if_else(ENTREZID %in% AC_share_var, "y","no")) %>% 
  mutate(not_AC=if_else(ENTREZID %in% not_AC_shared,"y","no")) %>% 
  mutate(AC_shared_sig=if_else(ENTREZID %in% AC_shared_sig,"y","no")) %>% 
  # group_by(AC_shared_sig,not_AC)  %>% 
    summarise("var_share-n" = sum(not_AC=="no"&AC_shared_sig=="no"), "var_share-y"=sum(not_AC=="no"&AC_shared_sig=="y"),"not_var-n"=sum(not_AC=="y"&AC_shared_sig=="no"), "not_var-y"=sum(not_AC=="y"&AC_shared_sig=="y")) %>% 
    pivot_longer(everything(), names_to = "set", values_to = "count") %>% 
    separate(set, into = c("set", "color"),sep="-" ) %>% 
    mutate(color, factor(color, levels = c("y","no"))) %>% 
    mutate(set=case_match(set,"not_var"~"not AC shared\nvar. gene","var_share"~"AC shared\nvar. gene")) %>% 
   ggplot( ., aes(x=set, y=count, group=color,fill=color))+
     geom_col(position='fill')+
      theme_classic()+
   scale_color_manual(values=drug_palc)+
     scale_fill_manual(values=c("y"="cornflowerblue","n"="darkblue"), 
                    labels=c("not an AC-sp gene","shared with\nAC sp"))+
       scale_y_continuous(expand=expansion(0.001))+
    theme(strip.text=element_text(size=10, face = "bold"),
          axis.text.x = element_text(margin = margin(2,0,2,0, "pt"), size=12),
  strip.background = element_rect (linetype=1, linewidth = 0.5))
 

testmat <- matrix(c(88,4347,115,9534),nrow = 2,byrow = TRUE)

chisq.test(testmat)#$p.value
  

```



## Top2i shared


```{r enrichment top2bi checks}

TOP2i_share_var <- venn24part$..values..[[17]] # 32
not_T2_shared <- setdiff(expressedgenes$ENTREZID,TOP2i_share_var)#14052
TOP2i_shared_sig <- sig_24_venn$..values..[[1]] ##882
length(intersect(TOP2i_share_var,TOP2i_shared_sig))  #(3 overlap)
length(intersect(not_T2_shared,TOP2i_shared_sig)) #879

# stored <-
  expressedgenes %>% 
  mutate(var_t2= if_else(ENTREZID %in% TOP2i_share_var, "y","no")) %>% 
  mutate(not_t2= if_else(ENTREZID %in% not_T2_shared,"y","no")) %>% 
  mutate(T2_shared_sig=if_else(ENTREZID %in% TOP2i_shared_sig,"y","no")) %>% 
  # group_by(AC_shared_sig,not_t2)  %>%
    summarise("var_share-n" = sum(not_t2=="no"&T2_shared_sig=="no"), "var_share-y"=sum(not_t2=="no"&T2_shared_sig=="y"),"not_var-n"=sum(not_t2=="y"&T2_shared_sig=="no"), "not_var-y"=sum(not_t2=="y"&T2_shared_sig=="y"))%>% 
    pivot_longer(everything(), names_to = "set", values_to = "count") %>% 
    separate(set, into = c("set", "color"),sep="-" ) %>% 
    mutate(color, factor(color, levels = c("y","no"))) %>% 
    mutate(set=case_match(set,"not_var"~"not TOP2i shared\nvar. gene","var_share"~"TOP2i shared\nvar. gene")) %>% 
   ggplot( ., aes(x=set, y=count, group=color,fill=color))+
     geom_col(position='fill')+
      theme_classic()+
    xlab(" ")+
    ggtitle("TOP2i variable genes in TOP2i specific n= 4435")+
   scale_color_manual(values=drug_palc)+
     scale_fill_manual(values=c("y"="cornflowerblue","n"="darkblue"), 
                    labels=c("not a TOP2i-sp gene","shared with\nTOP2i-sp"))+
       scale_y_continuous(expand=expansion(0.001))+
    theme(strip.text=element_text(size=10, face = "bold"),
          axis.text.x = element_text(margin = margin(2,0,2,0, "pt"), size=12),
  strip.background = element_rect (linetype=1, linewidth = 0.5))
 

testmatTOP <- matrix(c(3,879,29,13173),nrow = 2,byrow = TRUE)

chisq.test(testmatTOP)#$p.value
  

```


## GO heatmaps  


```{r heatmap for  shared GO}

DOX_var24gost <- readRDS("data/DEG-GO/var/DOX_var24gost.RDS")
DOX_table <- DOX_var24gost$result %>% 
  dplyr::select(c(source, term_id, term_name,intersection_size, term_size, p_value))
EPI_var24gost <- readRDS("data/DEG-GO/var/EPI_var24gost.RDS")
EPI_table <- EPI_var24gost$result %>% 
  dplyr::select(c(source, term_id, term_name,intersection_size, term_size, p_value))
DNR_var24gost <- readRDS("data/DEG-GO/var/DNR_var24gost.RDS")
DNR_table <- DNR_var24gost$result %>% 
  dplyr::select(c(source, term_id, term_name,intersection_size, term_size, p_value))
MTX_var24gost <- readRDS("data/DEG-GO/var/MTX_var24gost.RDS")
MTX_table <- MTX_var24gost$result %>% 
  dplyr::select(c(source, term_id, term_name,intersection_size, term_size, p_value))
TRZ_var24gost <- readRDS("data/DEG-GO/var/TRZ_var24gost.RDS")
TRZ_table <- TRZ_var24gost$result %>% 
  dplyr::select(c(source, term_id, term_name,intersection_size, term_size, p_value))
AC_share_var24gost <- readRDS("data/DEG-GO/var/AC_share_var24gost.RDS")
AC_share_var24_table <- AC_share_var24gost$result %>% 
  dplyr::select(c(source, term_id, term_name,intersection_size, term_size, p_value))
TOP2i_var24gost <- readRDS("data/DEG-GO/var/TOP2i_var24gost.RDS")
TOP2i_var24_table <- TOP2i_var24gost$result %>% 
  dplyr::select(c(source, term_id, term_name,intersection_size, term_size, p_value))
terms <- list()
terms[1] <- DOX_table %>% dplyr::filter(source=="GO:BP") %>% slice_min(.,p_value, n=3) %>% list()
terms[2] <- EPI_table %>% dplyr::filter(source=="GO:BP") %>%slice_min(.,p_value, n=3) %>% list()
terms[3] <- DNR_table %>% dplyr::filter(source=="GO:BP") %>%slice_min(.,p_value, n=3) %>% list()
terms[4] <- MTX_table %>% dplyr::filter(source=="GO:BP") %>%slice_min(.,p_value, n=3) %>% list()
terms[5] <- TRZ_table %>% dplyr::filter(source=="GO:BP") %>%slice_min(.,p_value, n=3) %>% list()
terms[6] <- AC_share_var24_table %>% dplyr::filter(source=="GO:BP") %>%slice_min(.,p_value, n=3) %>% list()
terms[7] <- TOP2i_var24_table %>% dplyr::filter(source=="GO:BP") %>%slice_min(.,p_value, n=3) %>% list()
names(terms) <- c("DOX", "EPI","DNR", "MTX", "TRZ", "AC_shared", "TOP2i_shared")
termlist <- rbindlist(terms)
termlistid <- c("GO:0010867","GO:0043508","GO:0070932")
```





```{r actual heatmap}
P_valueterm <- list()
P_valueterm[1] <- DOX_table %>% dplyr::filter(term_id %in% termlistid) %>% list()
P_valueterm[2] <- EPI_table %>% dplyr::filter(term_id %in% termlistid) %>% list()
P_valueterm[3] <- DNR_table %>% dplyr::filter(term_id %in% termlistid) %>% list()
P_valueterm[4] <- MTX_table %>% dplyr::filter(term_id %in% termlistid) %>% list()
P_valueterm[5] <- TRZ_table %>% dplyr::filter(term_id %in% termlistid) %>% list()
P_valueterm[6] <- AC_share_var24_table %>% dplyr::filter(term_id %in% termlistid) %>% list()
P_valueterm[7] <- TOP2i_var24_table %>% dplyr::filter(term_id %in% termlistid) %>% list()

names(P_valueterm) <- c("DOX", "EPI","DNR", "MTX", "TRZ", "AC_shared", "TOP2i_shared")

GO_heatmapdata <- rbindlist(P_valueterm,idcol= "deg")
col_funkegg= circlize::colorRamp2(c(0, 5), c("white", "darkred"))


GO_sig_mat <- GO_heatmapdata %>% 
  dplyr::select(deg,p_value,term_name) %>%
# mutate(term_name= case_match(term_name,"Cell cycle"~"Cell\ncycle","p53 signaling pathway"~"p53\nsig.\npath.","Base excision repair"~"Base\nexcision\nrepair",	
# "DNA replication"~"DNA\nrep.",.default = term_name)) %>% 
  pivot_wider(id_cols = everything(),
              names_from="term_name",
              values_from="p_value",
              values_fill = list(p_value = 1)) %>% 
  column_to_rownames('deg') %>% 
  as.matrix()# 

GO_mat<- GO_heatmapdata%>%
  mutate(log_val= (-log10(p_value))) %>% 
  dplyr::select(deg,log_val,term_name) %>%
  mutate(term_name= case_match(term_name,"histone H3 deacetylation"~"histone H3\n deacetylation","negative regulation of JUN kinase activity
"~"neg. reg. of\nJUN kinase\nactivity","positive regulation of triglyceride biosynthetic process"~"pos. reg.\nof triglyceride\nbiosynthetic\nprocess",.default = term_name)) %>%
  pivot_wider(id_cols = everything(),
              names_from="term_name",values_from="log_val") %>% 
  column_to_rownames('deg') %>% 
  as.matrix()# 

Heatmap(GO_mat,
        column_title = "GO -log10 p values",
        name = "-log10 (p value)",
        cluster_rows = FALSE, 
        cluster_columns = FALSE,
        column_names_rot = 0,
        column_dend_side = "bottom",
        
        column_names_max_height = unit(12,"cm"),
        column_names_centered = TRUE,
        row_names_max_width = max_text_width(
        rownames(GO_mat), 
        gp = gpar(fontsize = 10)),
        col = col_funkegg,
        na_col="lightyellow",
        column_labels = paste0(c("histone H3\n deacetylation",
                                    "neg. reg. of\nJUN kinase\nactivity",
                                    "pos. reg.of\ntriglyceride\nbiosynthetic\nprocess")),
        cell_fun = function(j, i, x, y, width, height, fill) {
        if(GO_sig_mat[i, j]< 0.05)
            grid.text("*", x, y, gp = gpar(fontsize = 20))
})
  

```

###  Seoane data investigation of variability
 
 I will examine the Seoane gene sets and overlap with variable data 

```{r Seoane overlap1}
list2env(Vargenes, envir = .GlobalEnv)
chrom_reg_Seoane <- read_csv(file = "data/Seonane2019supp1.txt",col_types = cols(...1 = col_skip()))
Seoane_2019 <- chrom_reg_Seoane[,2]
names(Seoane_2019) <- "ENTREZID"
Sup1seoane <- (unique(Seoane_2019$ENTREZID))
Sup4genes <- read.csv("output/Sup4seoane.csv", row.names = 1)
Sup4seoane <- Sup4genes  %>% 
  dplyr::filter(pval.expAnth<0.05) %>% 
  distinct(entrez, .keep_all = TRUE) %>% 
  dplyr::select(entrez) %>% 
  rename("ENTREZID"='entrez')

```
```{r venn seoane}

intersect(Sup1seoane,AC_share_var)
# 
intersect(Sup4seoane$ENTREZID,as.numeric(AC_share_var))
intersect(Sup4seoane$ENTREZID,as.numeric(not_AC_shared))
# Vargenes[[length(Vargenes)+1]] <- list(Sup4seoane$ENTREZID)

library(paletteer)
assignInNamespace(x="plot_venn", value=plot_venn, ns="ggVennDiagram")

sup1overlap <- list(as.numeric(DOX_24_var),as.numeric(EPI_24_var),as.numeric(DNR_24_var),as.numeric(MTX_24_var), Sup1seoane)
# re_incommon <- c(DOXreQTLs$ENTREZID,sigVDA24$ENTREZID, sigVEP24$ENTREZID, sigVMT24$ENTREZID)
# 
# names(reQTL_overlapDE24) <- c("Dox_reQTLS", "DNR DEGs","EPI DEGs","MTX DEGs")

ggVennDiagram::ggVennDiagram(sup1overlap,
                             category.names = c("DOX var",
                                     "EPI var",
                                      "DNR var",
                                 "MTX var",
                                 "Seoane S1"),
              show_intersect = FALSE,
              set_color = "black",
              # category_size = c(6,6,6,6),
              label = "count",
              # color =  c("DOX\negenes" = "yellow","DNR DEGs" ="steelblue","EPI DEGs" = 'red', "MTX DEGs" = 'black') ,
          
              label_percent_digit = 1,
              label_size = 4,
              label_alpha = 0,
              label_color = "black",
              edge_lty = "solid", set_size = 4.5)+
  scale_x_continuous(expand = expansion(mult = .3))+
  scale_y_continuous(expand = expansion(mult = .2))+
  # scale_color_paletteer_d(palette = "fishualize::Bodianus_pulchellus")+
  # scale_colour_gradientn(colours = cols, 
  #                      values = rescale(c(0, 20, 75, 1000, 5000)),
  #                      guide = "colorbar", limits=c(0, 100)) +
  scale_fill_distiller(palette="Spectral", direction = -1, limits= c(1,200),oob=scales::squish)#+
  # scale_fill_manual(values = cbp1)+
  labs(title = "24 hour DOX egenes in other DEG sets")+
  theme(plot.title = element_text(size = rel(1.6), hjust = 0.5, vjust =1))



```


```{r supp4}


sup4overlap <- list(as.numeric(DOX_24_var),as.numeric(EPI_24_var),as.numeric(DNR_24_var),as.numeric(MTX_24_var), as.numeric(Sup4seoane$ENTREZID))
ggVennDiagram::ggVennDiagram(sup4overlap,
                             category.names = c("DOX var",
                                     "EPI var",
                                      "DNR var",
                                 "MTX var",
                                 "Seoane S4"),
              show_intersect = FALSE,
              set_color = "black",
              # category_size = c(6,6,6,6),
              label = "count",
              # color =  c("DOX\negenes" = "yellow","DNR DEGs" ="steelblue","EPI DEGs" = 'red', "MTX DEGs" = 'black') ,
          
              label_percent_digit = 1,
              label_size = 4,
              label_alpha = 0,
              label_color = "black",
              edge_lty = "solid", set_size = 4.5)+
  scale_x_continuous(expand = expansion(mult = .3))+
  scale_y_continuous(expand = expansion(mult = .2))+
  # scale_color_paletteer_d(palette = "fishualize::Bodianus_pulchellus")+
  # scale_colour_gradientn(colours = cols, 
  #                      values = rescale(c(0, 20, 75, 1000, 5000)),
  #                      guide = "colorbar", limits=c(0, 100)) +
  scale_fill_distiller(palette="Spectral", direction = -1, limits= c(1,200),oob=scales::squish)#+
  # scale_fill_manual(values = cbp1)+
  labs(title = "24 hour DOX egenes in other DEG sets")+
  theme(plot.title = element_text(size = rel(1.6), hjust = 0.5, vjust =1))
```

```{r   overlap with degs}

DEG <- Vargenes
siglist24 <- siglist[6:9]
test <- siglist24[1]["ENTREZID"]
sig_24_ENTREZID <- sapply(siglist24,"[[",1)
all_unique_DEG <- unique(rbindlist(lapply(sig_24_ENTREZID, as.data.table))) ##8188
all_unique_var <- unique(rbindlist((lapply(Vargenes, as.data.table))))

length(intersect(all_unique_DEG$V1,all_unique_var$V1))##2190
DEG_var <- intersect(all_unique_DEG$V1,all_unique_var$V1)
non_DEG_var <- setdiff(expressedgenes$ENTREZID,DEG_var)

ggVennDiagram::ggVennDiagram(list(all_unique_var$V1, all_unique_DEG$V1),
                             category.names = c("all var genes", "all DEGs"),
              show_intersect = FALSE,
              set_color = "black",
              label = "count",
              label_percent_digit = 1,
              label_size = 4,
              label_alpha = 0,
              label_color = "black",
              edge_lty = "solid", set_size = 4.5)+
  scale_x_continuous(expand = expansion(mult = .3))+
  scale_y_continuous(expand = expansion(mult = .2))+
  # scale_color_paletteer_d(palette = "fishualize::Bodianus_pulchellus")+
  # scale_colour_gradientn(colours = cols, 
  #                      values = rescale(c(0, 20, 75, 1000, 5000)),
  #                      guide = "colorbar", limits=c(0, 100)) +
  scale_fill_distiller(palette="Spectral", direction = -1, limits= c(1000,8000),oob=scales::squish)#+
holdlist <-  list(DEG_var, as.numeric(non_DEG_var), Sup1seoane)
ggVennDiagram::ggVennDiagram(list( as.numeric(DEG_var), as.numeric(non_DEG_var), Sup1seoane),
                             category.names = c("DEG var", "non DEG var","Seoane supp 1"),
              show_intersect = FALSE,
              set_color = "black",
              label = "count",
              label_percent_digit = 1,
              label_size = 4,
              label_alpha = 0,
              label_color = "black",
              edge_lty = "solid", set_size = 4.5)+
  scale_x_continuous(expand = expansion(mult = .3))+
  scale_y_continuous(expand = expansion(mult = .2))+
  # scale_color_paletteer_d(palette = "fishualize::Bodianus_pulchellus")+
  # scale_colour_gradientn(colours = cols, 
  #                      values = rescale(c(0, 20, 75, 1000, 5000)),
  #                      guide = "colorbar", limits=c(0, 100)) +
  scale_fill_distiller(palette="Spectral", direction = -1, limits= c(1000,8000),oob=scales::squish)#+


testS1 <- matrix(c(59,271,2131,11623),nrow = 2,byrow = TRUE)

chisq.test(testS1)





```



## Burridge data 
```{r burrgenes}
DOXreQTLs <- readRDS("output/DOXreQTLs.RDS")
burr_genes <-  readRDS("data/BurridgeDOXTOX.RDS")
# BurridgeDOXTOX <-  getBM(attributes=my_attributes,filters ='hgnc_symbol',
#          values = burr_genes, mart = ensembl)
# BurridgeDOXTOX <- BurridgeDOXTOX %>% distinct(entrezgene_id, .keep_all = TRUE)
# saveRDS(BurridgeDOXTOX, "data/BurridgeDOXTOX.RDS") 


storeEPI <- readRDS("data/qvalueEPItemp.RDS")
VennDiagram::get.venn.partitions(list(storeEPI$ENTREZID, DOXreQTLs$ENTREZID))
intersect(DOXreQTLs$ENTREZID, burr_genes$entrezgene_id)
# DOX_reqtls <-$ENTREZID %>% as.integer()
  DOXreQTLs %>% dplyr::filter(ENTREZID %in% storeEPI$ENTREZID) %>%  tally( )
 burr_genes %>% 
   dplyr::filter(entrezgene_id%in% backGL$ENTREZID) %>% 
   dplyr::filter(entrezgene_id %in% storeEPI$ENTREZID)



### now for burr genes and epi508
VennDiagram::get.venn.partitions(list(storeEPI$ENTREZID, burr_genes$entrezgene_id))
### looking at the overlap of egenes and  EPI 508 var

storeEPI %>% 
  dplyr::filter (ENTREZID %in% DOXreQTLs$ENTREZID) %>% 
  left_join(., backGL, by=c("ENTREZID"))



```



### looking at heatmaps
```{r Variance heatmaps}
mean_vardrug1 <- read.csv("data/mean_vardrug1.csv", row.names = 1)


drug_frame <- mean_vardrug1 %>%
  rownames_to_column(var = "entrezid") %>%
  pivot_longer(cols = mean.Da.3:var.Ve.24,
               names_to = "short",
               values_to = "values") %>%
  separate(short, into = c("calc", "treatment", "time")) %>%
  # mutate(treatment = factor(
  #   treatment,
  #   levels = c("Do", "Ep", "Da", "Mi", "Tr", "Ve"),
  #   labels = c("DOX", "EPI", "DNR", "MTX", "TRZ", "VEH")
  # )) %>%
  # mutate(time = factor(
  #   time,
  #   levels = c("3", "24"),
  #   labels = c("3 hours", "24 hours")
  # )) %>%
  # group_by(treatment, time, calc) %>%
  as.data.frame

```


```{r individual matrix}

v_DNR_24 <- drug_frame %>% 
  dplyr::filter(calc !="mean", treatment =="Da", time=="24") %>% 
  select(entrezid,values)%>% 
  rename("DNR"="values")
  
v_DOX_24 <- drug_frame %>% 
  dplyr::filter(calc !="mean", treatment =="Do", time=="24") %>% 
  select(entrezid,values)%>% 
  rename("DOX"="values")

v_EPI_24 <- drug_frame %>% 
  dplyr::filter(calc !="mean", treatment =="Ep", time=="24") %>% 
  select(entrezid,values)%>% 
  rename("EPI"="values")

v_MTX_24 <- drug_frame %>% 
  dplyr::filter(calc !="mean", treatment =="Mi", time=="24") %>% 
  select(entrezid,values)%>% 
  rename("MTX"="values")

v_TRZ_24 <- drug_frame %>% 
  dplyr::filter(calc !="mean", treatment =="Tr", time=="24") %>% 
  select(entrezid,values)%>% 
  rename("TRZ"="values")

v_VEH_24 <- drug_frame %>% 
  dplyr::filter(calc !="mean", treatment =="Ve", time=="24") %>% 
  select(entrezid,values)%>% 
  rename("VEH"="values")
        
val_mat_24 <- left_join(v_DNR_24,v_DOX_24,
                        by=c("entrezid"))%>%
  left_join(.,v_EPI_24, by=c("entrezid")) %>%
  left_join(.,v_MTX_24, by=c("entrezid")) %>% 
  left_join(.,v_TRZ_24, by=c("entrezid")) %>% 
  left_join(.,v_VEH_24, by=c("entrezid")) %>% 
  column_to_rownames("entrezid") %>% 
  as.matrix
summary(val_mat_24)
col_fun = circlize::colorRamp2(c(0, 0.4, 2), c("#377EB8", "white", "#E41A1C"))
Heatmap(val_mat_24, col=col_fun,
        show_row_names = FALSE, 
        # width = unit(5, "mm"),
        cluster_columns = FALSE)


```



```{r eval=FALSE, include=FALSE}




DNR.VEH.24 <- organized_drugframe %>% 
  dplyr::select(c(starts_with("Da")&ends_with("24h")),
         c(starts_with("Ve")&ends_with("24h"))) %>%
  rowwise() %>% 
  mutate(broom::tidy(var.test(c_across(starts_with("Da")),c_across(starts_with("Ve")))))
  
```


