---
title: "Variance"
author: "ERM"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                message=FALSE, 
                warning=FALSE)
```

```{r package loading}

library(tidyverse)
library(ggpubr)
library(ggsignif)
library(gprofiler2)
library(paletteer)
library(ggVennDiagram)
library(gridtext)
library(scales)
library(kableExtra)

```

## initial calculations and data loading  


```{r data loading, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
filcpm_counts <- read.csv("data/filtered_cpm_counts.csv", row.names = 1)
time <- rep((rep(c("3h", "24h"), c(6,6))), 6) 
time <- ordered(time, levels =c("3h", "24h"))

indv <- as.factor(rep(c(1,2,3,4,5,6), c(12,12,12,12,12,12))) 


group <-(rep(c("1","2","3","4","5","6","7","8","9","10","11","12"),6)) 
group <- factor(group,levels = c( 1,2,3,4,5,6,7,8,9,10,11,12))

drug <- rep(c("DNR","DOX","EPI","MTX","TRZ", "VEH"),12)


mean_varframe <- filcpm_counts %>% 
  rowwise() %>% 
  mutate(mean.1.3=mean(c_across(Da.1.3h:Ve.1.3h)),
         var.1.3=var(c_across(Da.1.3h:Ve.1.3h)),
         mean.2.3=mean(c_across(Da.2.3h:Ve.2.3h)),
         var.2.3=var(c_across(Da.2.3h:Ve.2.3h)),
         mean.3.3=mean(c_across(Da.3.3h:Ve.3.3h)),
         var.3.3=var(c_across(Da.3.3h:Ve.3.3h)),
         mean.4.3=mean(c_across(Da.4.3h:Ve.4.3h)),
         var.4.3=var(c_across(Da.4.3h:Ve.4.3h)),
         mean.5.3=mean(c_across(Da.5.3h:Ve.5.3h)),
         var.5.3=var(c_across(Da.5.3h:Ve.5.3h)),
         mean.6.3=mean(c_across(Da.6.3h:Ve.6.3h)),
         var.6.3=var(c_across(Da.6.3h:Ve.6.3h)),
         mean.1.24=mean(c_across(Da.1.24h:Ve.1.24h)),
         var.1.24=var(c_across(Da.1.24h:Ve.1.24h)),
         mean.2.24=mean(c_across(Da.2.24h:Ve.2.24h)),
         var.2.24=var(c_across(Da.2.24h:Ve.2.24h)),
         mean.3.24=mean(c_across(Da.3.24h:Ve.3.24h)),
         var.3.24=var(c_across(Da.3.24h:Ve.3.24h)),
         mean.4.24=mean(c_across(Da.4.24h:Ve.4.24h)),
         var.4.24=var(c_across(Da.4.24h:Ve.4.24h)),
         mean.5.24=mean(c_across(Da.5.24h:Ve.5.24h)),
         var.5.24=var(c_across(Da.5.24h:Ve.5.24h)),
         mean.6.24=mean(c_across(Da.6.24h:Ve.6.24h)),
         var.6.24=var(c_across(Da.6.24h:Ve.6.24h))) 


  
  rownames(mean_varframe) <- rownames(filcpm_counts)
 
write.csv(mean_varframe,"data/mean_varframe.csv")


```

### by drug  

```{r manip mean across indv, eval=FALSE,echo=FALSE }
filcpm_counts <- read.csv("data/filtered_cpm_counts.csv", row.names = 1)

mean_vardrug <- filcpm_counts %>% 
 select(c(starts_with("Da")&ends_with("24h")),
        c(starts_with("Do")&ends_with("24h")),
        c(starts_with("Ep")&ends_with("24h")),
        c(starts_with("Mi")&ends_with("24h")),
        c(starts_with("Tr")&ends_with("24h")),
        c(starts_with("Ve")&ends_with("24h")),
       c(starts_with("Da")&ends_with("3h")),
        c(starts_with("Do")&ends_with("3h")),
        c(starts_with("Ep")&ends_with("3h")),
        c(starts_with("Mi")&ends_with("3h")),
        c(starts_with("Tr")&ends_with("3h")),
        c(starts_with("Ve")&ends_with("3h")))
        
  rownames(mean_vardrug) <- rownames(filcpm_counts)  
 write.csv(mean_vardrug, "data/organized_drugframe.csv")
        
        
mean_vardrug1 <- mean_vardrug %>% 
rowwise() %>% 
  mutate(mean.Da.3=mean(c_across(Da.1.3h:Da.6.3h)),
         var.Da.3=var(c_across(Da.1.3h:Da.6.3h)),
         mean.Do.3=mean(c_across(Do.1.3h:Do.6.3h)),
         var.Do.3=var(c_across(Do.1.3h:Do.6.3h)),
         mean.Ep.3=mean(c_across(Ep.1.3h:Ep.6.3h)),
         var.Ep.3=var(c_across(Ep.1.3h:Ep.6.3h)),
         mean.Mi.3=mean(c_across(Mi.1.3h:Mi.6.3h)),
         var.Mi.3=var(c_across(Mi.1.3h:Mi.6.3h)),
         mean.Tr.3=mean(c_across(Tr.1.3h:Tr.6.3h)),
         var.Tr.3=var(c_across(Tr.1.3h:Tr.6.3h)),
         mean.Ve.3=mean(c_across(Ve.1.3h:Ve.6.3h)),
         var.Ve.3=var(c_across(Ve.1.3h:Ve.6.3h)),
         mean.Da.24=mean(c_across(Da.1.24h:Da.6.24h)),
         var.Da.24=var(c_across(Da.1.24h:Da.6.24h)),
         mean.Do.24=mean(c_across(Do.1.24h:Do.6.24h)),
         var.Do.24=var(c_across(Do.1.24h:Do.6.24h)),
         mean.Ep.24=mean(c_across(Ep.1.24h:Ep.6.24h)),
         var.Ep.24=var(c_across(Ep.1.24h:Ep.6.24h)),
         mean.Mi.24=mean(c_across(Mi.1.24h:Mi.6.24h)),
         var.Mi.24=var(c_across(Mi.1.24h:Mi.6.24h)),
         mean.Tr.24=mean(c_across(Tr.1.24h:Tr.6.24h)),
         var.Tr.24=var(c_across(Tr.1.24h:Tr.6.24h)),
         mean.Ve.24=mean(c_across(Ve.1.24h:Ve.6.24h)),
         var.Ve.24=var(c_across(Ve.1.24h:Ve.6.24h))) %>% 
         select(mean.Da.3:var.Ve.24)
rownames(mean_vardrug1) <- rownames(filcpm_counts)
write.csv(mean_vardrug1,"data/mean_vardrug1.csv")



```

###  plot by drug  

```{r graph of var by drug indv, fig.height=5, fig.width=5}
mean_vardrug1 <- read.csv("data/mean_vardrug1.csv", row.names = 1)


drug_frame<- mean_vardrug1 %>% 
  rownames_to_column(var = "entrezid") %>% 
  pivot_longer(cols = mean.Da.3:var.Ve.24, names_to = "short", values_to = "values") %>% 
  separate(short, into=c("calc","treatment","time")) %>% 
  mutate(treatment= factor(treatment, levels = c("Do","Ep","Da","Mi","Tr","Ve"),labels = c("DOX","EPI","DNR","MTX","TRZ","VEH"))) %>% 
  mutate(time= factor(time, levels = c("3","24"), labels= c("3 hours","24 hours"))) %>% 
  group_by(treatment, time, calc) %>% 
  as.data.frame



drug_frame %>% 
  filter(calc!="mean") %>% 
  ggplot(., aes(x= treatment, y=values))+
  geom_boxplot()+
  geom_signif(comparisons =list(c("DOX","VEH"),
                                c("EPI","VEH"),
                                c("DNR","VEH"),
                                c("MTX","VEH"),
                                c("TRZ","VEH")),
              test= "t.test",
              map_signif_level=FALSE,
              textsize =4,
              step_increase = 0.1)+
  facet_wrap(~time)+
  ggtitle("var")+
  ylim(0,0.5)
drug_frame %>% 
  filter(calc!="mean") %>% 
  ggplot(., aes(x= treatment, y=values))+
  geom_boxplot()+
  geom_signif(comparisons =list(c("DOX","VEH"),
                                c("EPI","VEH"),
                                c("DNR","VEH"),
                                c("MTX","VEH"),
                                c("TRZ","VEH")),
              test= "t.test",
              map_signif_level=FALSE,
              textsize =4,
              step_increase = 0.1)+
  facet_wrap(~time)+
  ggtitle("var")#+
  # ylim(0,0.5)

drug_frame %>% 
  filter(calc!="var") %>% 
  ggplot(., aes(x= treatment, y=values))+
  geom_boxplot()+
  geom_signif(comparisons =list(c("TRZ","VEH"),
                                c("MTX","VEH"),
                                c("DNR","VEH"),
                                c("EPI","VEH"),
                                c("DOX","VEH")),
              test= "t.test",
              map_signif_level=FALSE,
              textsize =4,
              step_increase = 0.05)+
  facet_wrap(.~time)+
  ggtitle("Means")+
  ylim(0,18)


```


```{r evaluate eGenes in var}
mean_vardrug1 <- read.csv("data/mean_vardrug1.csv",row.names = 1)
my_exp_genes <- read.csv("data/backGL.txt")
GTEx_genes <- read.csv("data/GTEx_gene_list.csv",row.names = 1)
GTEx <- intersect(GTEx_genes$entrezgene_id,my_exp_genes$ENTREZID)
knowles5 <-readRDS("output/knowles5.RDS")


drug_frame2<- mean_vardrug1 %>% 
  rownames_to_column(var = "entrezid") %>% 
  filter(entrezid %in%knowles5$entrezgene_id) %>% 
  pivot_longer(cols = mean.Da.3:var.Ve.24, names_to = "short", values_to = "values") %>% 
  separate(short, into=c("calc","treatment","time")) %>% 
  mutate(treatment= factor(treatment, levels = c("Do","Ep","Da","Mi","Tr","Ve"),labels = c("DOX","EPI","DNR","MTX","TRZ","VEH"))) %>% 
  mutate(time= factor(time, levels = c("3","24"), labels= c("3 hours","24 hours"))) %>% 
  group_by(treatment, time, calc) %>% 
  as.data.frame

ggplot(drug_frame2, aes(x= treatment, y=values))+
  geom_boxplot()+
  geom_signif(comparisons =list(c("DOX","VEH"),
                                c("EPI","VEH"),
                                c("DNR","VEH"),
                                c("MTX","VEH"),
                                c("TRZ","VEH")),
              test= "t.test",
              map_signif_level=TRUE,
              textsize =4,
              step_increase = 0.1)+
  # stat_compare_means(method= "anova", label.y=15, label.x =2)+
  facet_wrap(time~calc, scales = "free_y")

  drug_frame2 %>% 
  filter(calc!="mean") %>% 
  ggplot(., aes(x= treatment, y=values))+
  geom_boxplot()+
  geom_signif(comparisons =list(c("DOX","VEH"),
                                c("EPI","VEH"),
                                c("DNR","VEH"),
                                c("MTX","VEH"),
                                c("TRZ","VEH")),
              test= "t.test",
              map_signif_level=TRUE,
              textsize =4,
              step_increase = 0.1)+
  facet_wrap(~time)+
  ggtitle("var using response eGenes")+
  ylim(0,1.0)

drug_frame2 %>% 
  filter(calc!="var") %>% 
  ggplot(., aes(x= treatment, y=values))+
  geom_boxplot()+
  geom_signif(comparisons =list(c("TRZ","VEH"),
                                c("MTX","VEH"),
                                c("DNR","VEH"),
                                c("EPI","VEH"),
                                c("DOX","VEH")),
              test= "t.test",
              map_signif_level=TRUE,
              textsize =4,
              step_increase = 0.05)+
  facet_wrap(.~time)+
  ggtitle("Means using response eGenes")+
  ylim(0,18)

  
```



```{r data wrangling-evalute variance, message=FALSE, warning=FALSE, eval=FALSE}

organized_drugframe <- read.csv("data/organized_drugframe.csv",
                                row.names = 1)

DNR.VEH.24 <- organized_drugframe %>% 
  select(c(starts_with("Da")&ends_with("24h")),
         c(starts_with("Ve")&ends_with("24h"))) %>%
  rowwise() %>% 
  mutate(data=list(var.test(c_across(starts_with("Da")),c_across(starts_with("Ve"))))) 
DOX.VEH.24 <- organized_drugframe %>% 
  select(c(starts_with("Do")&ends_with("24h")),
         c(starts_with("Ve")&ends_with("24h"))) %>%
 rowwise() %>% 
  mutate(data=list(var.test(c_across(starts_with("Do")),c_across(starts_with("Ve")))))

EPI.VEH.24 <- organized_drugframe %>% 
  select(c(starts_with("Ep")&ends_with("24h")),
         c(starts_with("Ve")&ends_with("24h"))) %>%
 rowwise() %>% 
  mutate(data=list(var.test(c_across(starts_with("Ep")),c_across(starts_with("Ve")))))

MTX.VEH.24 <- organized_drugframe %>% 
  select(c(starts_with("Mi")&ends_with("24h")),
         c(starts_with("Ve")&ends_with("24h"))) %>%
  rowwise() %>% 
  mutate(data=list(var.test(c_across(starts_with("Mi")),c_across(starts_with("Ve")))))
TRZ.VEH.24 <- organized_drugframe %>% 
  select(c(starts_with("Tr")&ends_with("24h")),
         c(starts_with("Ve")&ends_with("24h"))) %>%
  rowwise() %>% 
  mutate(data=list(var.test(c_across(starts_with("Tr")),c_across(starts_with("Ve")))))

DNR.VEH.3 <- organized_drugframe %>% 
  select(c(starts_with("Da")&ends_with("3h")),
         c(starts_with("Ve")&ends_with("3h"))) %>%
  rowwise() %>% 
  mutate(data=list(var.test(c_across(starts_with("Da")),c_across(starts_with("Ve")))))
DOX.VEH.3 <- organized_drugframe %>% 
  select(c(starts_with("Do")&ends_with("3h")),
         c(starts_with("Ve")&ends_with("3h"))) %>%
  rowwise() %>% 
  mutate(data=list(var.test(c_across(starts_with("Do")),c_across(starts_with("Ve"))))) 
EPI.VEH.3 <- organized_drugframe %>% 
  select(c(starts_with("Ep")&ends_with("3h")),
         c(starts_with("Ve")&ends_with("3h"))) %>%
  rowwise() %>% 
  mutate(data=list(var.test(c_across(starts_with("Ep")),c_across(starts_with("Ve")))))
MTX.VEH.3 <- organized_drugframe %>% 
  select(c(starts_with("Mi")&ends_with("3h")),
         c(starts_with("Ve")&ends_with("3h"))) %>%
  rowwise() %>% 
  mutate(data=list(var.test(c_across(starts_with("Mi")),c_across(starts_with("Ve")))))


TRZ.VEH.3 <- organized_drugframe %>% 
  rownames_to_column(.id = "gene") %>% 
  rowwise() %>% 
  select(c(starts_with("Tr")&ends_with("3h")),
         c(starts_with("Ve")&ends_with("3h"))) %>%
  mutate(data=list(var.test(c_across(starts_with("Tr")),c_across(starts_with("Ve")))))

Var_test_list24 <- list(DNR.VEH.24,DOX.VEH.24,EPI.VEH.24,MTX.VEH.24,TRZ.VEH.24)
                      
names(Var_test_list24) <- c('DNR.VEH.24','DOX.VEH.24','EPI.VEH.24','MTX.VEH.24','TRZ.VEH.24')
                    
  
 saveRDS(Var_test_list24,"data/Var_test_list24.RDS")   
 
 
 Var_test_list3 <- list(DNR.VEH.3,DOX.VEH.3,EPI.VEH.3,MTX.VEH.3,TRZ.VEH.3)
                      
names(Var_test_list3) <- c('DNR.VEH.3','DOX.VEH.3','EPI.VEH.3','MTX.VEH.3','TRZ.VEH.3')
                     saveRDS(Var_test_list3,"data/Var_test_list3.RDS") 
```       

```{r extract pvalue list}

                 
organized_drugframe <- read.csv("data/organized_drugframe.csv",
                                row.names = 1)
Var_test_list3 <- readRDS("data/Var_test_list3.RDS")
set3 <- names(Var_test_list3)
shorterlist <- Var_test_list3[[1]][[13]]
names(shorterlist) <- rownames(organized_drugframe)

framefun <- data.frame(ENTREZID=rownames(organized_drugframe))
for (i in 1:length(set3)){
  a <- set3[i]
    s_list<- Var_test_list3[[i]][[13]]
  names(s_list) <- rownames(organized_drugframe)
  hold<- map_df(s_list, ~as.data.frame(.x$p.value), .id="ENTREZID")
   framefun[paste0(a)] <- hold$`.x$p.value`
 
}
Var_test_list24 <- readRDS("data/Var_test_list24.RDS")
set24 <- names(Var_test_list24) 

framefun24 <- data.frame(ENTREZID=rownames(organized_drugframe))
for (i in 1:length(set24)){
  a <- set24[i]
    s_list<- Var_test_list24[[i]][[13]]
  names(s_list) <- rownames(organized_drugframe)
  hold<- map_df(s_list, ~as.data.frame(.x$p.value), .id="ENTREZID")
   framefun24[paste0(a)] <- hold$`.x$p.value`
 
}

```

## 3 and 24 hour histogram of var
```{r plot pvalue as histo}
framefun %>% 
  pivot_longer(col=!ENTREZID,names_to= "combo", values_to = "p.value") %>% 
  separate(combo, into= c("drug", NA,"time")) %>%
  mutate(drug = factor(drug, levels = c("DOX", "EPI", "DNR","MTX", "TRZ"))) %>% 
  ggplot(.,aes(x=p.value,col=drug,fill=drug))+
  geom_histogram()+
  facet_wrap(~drug)+
  ggtitle("3 hour var.test p.value")


framefun24 %>% 
  pivot_longer(col=!ENTREZID,names_to= "combo", values_to = "p.value") %>% 
  separate(combo, into= c("drug", NA,"time")) %>%
  mutate(drug = factor(drug, levels = c("DOX", "EPI", "DNR","MTX", "TRZ"))) %>% 
  ggplot(.,aes(x=p.value,col=drug,fill=drug))+
  geom_histogram()+
  facet_wrap(~drug)+
  ggtitle("24 hour var.test p.value")
  


```

```{r gene filtering}
backGL <-read_csv("data/backGL.txt", 
    col_types = cols(...1 = col_skip()))
var3 <- list <- framefun %>% 
  pivot_longer(col=!ENTREZID,names_to= "combo", values_to = "p.value") %>% 
  separate(combo, into= c("drug", NA,"time")) %>%
  mutate(drug = factor(drug, levels = c("DOX", "EPI", "DNR","MTX", "TRZ"))) %>% 
  filter(p.value<0.05)

var24 <- list <- framefun24 %>% 
  pivot_longer(col=!ENTREZID,names_to= "combo", values_to = "p.value") %>% 
  separate(combo, into= c("drug", NA,"time")) %>%
  mutate(drug = factor(drug, levels = c("DOX", "EPI", "DNR","MTX", "TRZ"))) %>% 
  filter(p.value<0.05)

DOX_24_var <- var24 %>% filter(drug=="DOX") %>% select(ENTREZID)#1089 
EPI_24_var <- var24 %>% filter(drug=="EPI")%>% select(ENTREZID)#2211
DNR_24_var <- var24 %>% filter(drug=="DNR")%>% select(ENTREZID)#928
MTX_24_var <- var24 %>% filter(drug=="MTX")%>% select(ENTREZID)#269
TRZ_24_var <- var24 %>% filter(drug=="TRZ")%>% select(ENTREZID)#157

geneset_24 <- list(DOX_24_var$ENTREZID, EPI_24_var$ENTREZID, DNR_24_var$ENTREZID, MTX_24_var$ENTREZID, TRZ_24_var$ENTREZID)
names(geneset_24) <- c("DOX_24_var","EPI_24_var","DNR_24_var" ,"MTX_24_var","TRZ_24_var")

DOX_3_var <- var3 %>% filter(drug=="DOX")%>% select(ENTREZID)#346
EPI_3_var <- var3 %>% filter(drug=="EPI")%>% select(ENTREZID)#332
DNR_3_var <- var3 %>% filter(drug=="DNR")%>% select(ENTREZID)#385
MTX_3_var <- var3 %>% filter(drug=="MTX")%>% select(ENTREZID)#277
TRZ_3_var <- var3 %>% filter(drug=="TRZ")%>% select(ENTREZID)#262

geneset_3 <- list(DOX_3_var$ENTREZID,EPI_3_var$ENTREZID,DNR_3_var$ENTREZID ,MTX_3_var$ENTREZID,TRZ_3_var$ENTREZID)
names(geneset_3) <- c("DOX_3_var","EPI_3_var","DNR_3_var" ,"MTX_3_var","TRZ_3_var")


```


## Venn

```{r venn of 24 hours}

ggVennDiagram::ggVennDiagram(geneset_24,
              category.names = c("DOX\nn = 1089 ",
                                 "EPI\nn = 2211\n",
                                 "DNR\nn = 928",
                                 "MTX\nn = 269", 
                                "TRZ\nn = 157"),
              show_intersect = FALSE,
              set_color = "black",
              category_size = c(6,6,6,6),
              label = "count",
              label_percent_digit = 1,
              label_size = 4,
              label_alpha = 0,
              label_color = "black",
              edge_lty = "solid", set_size = 4.5)+
  scale_x_continuous(expand = expansion(mult = .3))+
  scale_y_continuous(expand = expansion(mult = .2))+
  scale_color_paletteer_d(palette = "fishualize::Bodianus_pulchellus")+
  scale_fill_distiller(palette="Spectral", direction = -1)+
  labs(title = "24 hour var genes p. value <0.05",
       caption = paste("n =", length(unique(var24$ENTREZID)),"genes"))+
  
  theme(plot.title = element_text(size = rel(1.6), hjust = 0.5, vjust =1))

```

## 24 hour DOX

```{r GO analysis of DOX24}

# DOX_var24gost <- gost(query = DOX_24_var$ENTREZID,
#                   organism = "hsapiens",
#                   significant = FALSE,
#                   ordered_query = TRUE,
#                   domain_scope = "custom",
#                   measure_underrepresentation = FALSE,
#                   evcodes = FALSE,
#                   numeric_ns="ENTREZGENE",
#                   user_threshold = 0.05,
#                   correction_method = "fdr",
#                   custom_bg = backGL$ENTREZID,
#                   sources=c("GO:BP","KEGG"))

# saveRDS(DOX_var24gost,"data/DEG-GO/var/DOX_var24gost.RDS")
DOX_var24gost <- readRDS("data/DEG-GO/var/DOX_var24gost.RDS")

DOX_var24p <- gostplot(DOX_var24gost, capped = FALSE, interactive = TRUE)
DOX_var24p

DOX_var24_table <- DOX_var24gost$result %>% 
  dplyr::select(c(source, term_id, term_name,intersection_size, term_size, p_value))

DOX_var24_table %>% 
 dplyr::filter(source=="GO:BP") %>% 
    dplyr::select(p_value,term_name,intersection_size) %>%
    slice_min(., n=10 ,order_by=p_value) %>%
    mutate(log_val = -log10(p_value)) %>%
   # slice_max(., n=10,order_by = p_value) %>%
   ggplot(., aes(x = log_val, y =reorder(term_name,p_value), col= intersection_size)) +
    geom_point(aes(size = intersection_size)) +
   geom_vline(xintercept = (-log10(0.05)), col="red")+
    scale_y_discrete(labels = label_wrap(30))+
    guides(col="none", size=guide_legend(title = "# of intersected \n terms"))+
    ggtitle('DOX24 hour top 10 GO:BP terms') +
    xlab(expression(" -"~log[10]~("adj. p-value")))+
    ylab("GO: BP term")+
      theme_bw()+
    theme(plot.title = element_text(size = rel(1.5), hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.line = element_line(linewidth = 1.5),
        axis.text = element_text(size = 10, color = "black", angle = 0),
        strip.text.x = element_text(size = 15, color = "black", face = "bold")) 
  DOX_var24_table %>% 
    mutate_at(.vars = 6, .funs= scientific_format()) %>% 
  kable(.,caption = "DOX 24 enrichment terms of highly var genes") %>% 
  kable_paper("striped", full_width = FALSE) %>%  
  kable_styling(full_width = FALSE, position = "left",bootstrap_options = c("striped","hover")) %>% 
  scroll_box(width = "100%", height = "400px")



```
## 24 hour EPI

```{r GO analysis of EPI24}

# EPI_var24gost <- gost(query = EPI_24_var$ENTREZID,
#                   organism = "hsapiens",
#                   significant = FALSE,
#                   ordered_query = TRUE,
#                   domain_scope = "custom",
#                   measure_underrepresentation = FALSE,
#                   evcodes = FALSE,
#                   numeric_ns="ENTREZGENE",
#                   user_threshold = 0.05,
#                   correction_method = "fdr",
#                   custom_bg = backGL$ENTREZID,
#                   sources=c("GO:BP","KEGG"))
# 
# saveRDS(EPI_var24gost,"data/DEG-GO/var/EPI_var24gost.RDS")
EPI_var24gost <- readRDS("data/DEG-GO/var/EPI_var24gost.RDS")

EPI_var24p <- gostplot(EPI_var24gost, capped = FALSE, interactive = TRUE)
EPI_var24p

EPI_var24_table <- EPI_var24gost$result %>% 
  dplyr::select(c(source, term_id, term_name,intersection_size, term_size, p_value))

EPI_var24_table %>% 
 dplyr::filter(source=="GO:BP") %>% 
    dplyr::select(p_value,term_name,intersection_size) %>%
    slice_min(., n=3 ,order_by=p_value) %>%
    mutate(log_val = -log10(p_value)) %>%
   # slice_max(., n=10,order_by = p_value) %>%
   ggplot(., aes(x = log_val, y =reorder(term_name,p_value), col= intersection_size)) +
    geom_point(aes(size = intersection_size)) +
   geom_vline(xintercept = (-log10(0.05)), col="red")+
    scale_y_discrete(labels = label_wrap(30))+
    guides(col="none", size=guide_legend(title = "# of intersected \n terms"))+
    ggtitle('EPI24 hour top 10 GO:BP terms') +
    xlab(expression(" -"~log[10]~("adj. p-value")))+
    ylab("GO: BP term")+
      theme_bw()+
    theme(plot.title = element_text(size = rel(1.5), hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.line = element_line(linewidth = 1.5),
        axis.text = element_text(size = 10, color = "black", angle = 0),
        strip.text.x = element_text(size = 15, color = "black", face = "bold")) 
  EPI_var24_table %>% 
    mutate_at(.vars = 6, .funs= scientific_format()) %>% 
  kable(.,caption = "EPI 24 enrichment terms of highly var genes") %>% 
  kable_paper("striped", full_width = FALSE) %>%  
  kable_styling(full_width = FALSE, position = "left",bootstrap_options = c("striped","hover")) %>% 
  scroll_box(width = "100%", height = "400px")

EPI_var24_table %>% 
  filter(source=="KEGG") %>% 
    mutate_at(.vars = 6, .funs= scientific_format()) %>% 
  kable(.,caption = "KEGG EPI 24 hour enrichment terms of highly var genes") %>% 
  
  kable_paper("striped", full_width = FALSE) %>%  
  kable_styling(full_width = FALSE, position = "left",bootstrap_options = c("striped","hover")) %>% 
  scroll_box(width = "100%", height = "400px")


```


## 24 hour DNR

```{r GO analysis of DNR24}

# DNR_var24gost <- gost(query = DNR_24_var$ENTREZID,
#                   organism = "hsapiens",
#                   significant = FALSE,
#                   ordered_query = TRUE,
#                   domain_scope = "custom",
#                   measure_underrepresentation = FALSE,
#                   evcodes = FALSE,
#                   numeric_ns="ENTREZGENE",
#                   user_threshold = 0.05,
#                   correction_method = "fdr",
#                   custom_bg = backGL$ENTREZID,
#                   sources=c("GO:BP","KEGG"))
# 
# saveRDS(DNR_var24gost,"data/DEG-GO/var/DNR_var24gost.RDS")
DNR_var24gost <- readRDS("data/DEG-GO/var/DNR_var24gost.RDS")

DNR_var24p <- gostplot(DNR_var24gost, capped = FALSE, interactive = TRUE)
DNR_var24p

DNR_var24_table <- DNR_var24gost$result %>% 
  dplyr::select(c(source, term_id, term_name,intersection_size, term_size, p_value))

DNR_var24_table %>% 
 dplyr::filter(source=="GO:BP") %>% 
    dplyr::select(p_value,term_name,intersection_size) %>%
    slice_min(., n=3 ,order_by=p_value) %>%
    mutate(log_val = -log10(p_value)) %>%
   # slice_max(., n=10,order_by = p_value) %>%
   ggplot(., aes(x = log_val, y =reorder(term_name,p_value), col= intersection_size)) +
    geom_point(aes(size = intersection_size)) +
   geom_vline(xintercept = (-log10(0.05)), col="red")+
    scale_y_discrete(labels = label_wrap(30))+
    guides(col="none", size=guide_legend(title = "# of intersected \n terms"))+
    ggtitle('DNR24 hour top 10 GO:BP terms') +
    xlab(expression(" -"~log[10]~("adj. p-value")))+
    ylab("GO: BP term")+
      theme_bw()+
    theme(plot.title = element_text(size = rel(1.5), hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.line = element_line(linewidth = 1.5),
        axis.text = element_text(size = 10, color = "black", angle = 0),
        strip.text.x = element_text(size = 15, color = "black", face = "bold")) 
  DNR_var24_table %>% 
    mutate_at(.vars = 6, .funs= scientific_format()) %>% 
  kable(.,caption = "DNR 24 enrichment terms of highly var genes") %>% 
  kable_paper("striped", full_width = FALSE) %>%  
  kable_styling(full_width = FALSE, position = "left",bootstrap_options = c("striped","hover")) %>% 
  scroll_box(width = "100%", height = "400px")

DNR_var24_table %>% 
  filter(source=="KEGG") %>% 
    mutate_at(.vars = 6, .funs= scientific_format()) %>% 
  kable(.,caption = "KEGG DNR 24 hour enrichment terms of highly var genes") %>% 
  
  kable_paper("striped", full_width = FALSE) %>%  
  kable_styling(full_width = FALSE, position = "left",bootstrap_options = c("striped","hover")) %>% 
  scroll_box(width = "100%", height = "400px")


```



## 24 hour MTX

```{r GO analysis of MTX24}

# MTX_var24gost <- gost(query = MTX_24_var$ENTREZID,
#                   organism = "hsapiens",
#                   significant = FALSE,
#                   ordered_query = TRUE,
#                   domain_scope = "custom",
#                   measure_underrepresentation = FALSE,
#                   evcodes = FALSE,
#                   numeric_ns="ENTREZGENE",
#                   user_threshold = 0.05,
#                   correction_method = "fdr",
#                   custom_bg = backGL$ENTREZID,
#                   sources=c("GO:BP","KEGG"))
# 
# saveRDS(MTX_var24gost,"data/DEG-GO/var/MTX_var24gost.RDS")
MTX_var24gost <- readRDS("data/DEG-GO/var/MTX_var24gost.RDS")

MTX_var24p <- gostplot(MTX_var24gost, capped = FALSE, interactive = TRUE)
MTX_var24p

MTX_var24_table <- MTX_var24gost$result %>% 
  dplyr::select(c(source, term_id, term_name,intersection_size, term_size, p_value))

MTX_var24_table %>% 
 dplyr::filter(source=="GO:BP") %>% 
    dplyr::select(p_value,term_name,intersection_size) %>%
    slice_min(., n=10 ,order_by=p_value) %>%
    mutate(log_val = -log10(p_value)) %>%
   # slice_max(., n=10,order_by = p_value) %>%
   ggplot(., aes(x = log_val, y =reorder(term_name,p_value), col= intersection_size)) +
    geom_point(aes(size = intersection_size)) +
   geom_vline(xintercept = (-log10(0.05)), col="red")+
    scale_y_discrete(labels = label_wrap(30))+
    guides(col="none", size=guide_legend(title = "# of intersected \n terms"))+
    ggtitle('MTX24 hour top 10 GO:BP terms') +
    xlab(expression(" -"~log[10]~("adj. p-value")))+
    ylab("GO: BP term")+
      theme_bw()+
    theme(plot.title = element_text(size = rel(1.5), hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.line = element_line(linewidth = 1.5),
        axis.text = element_text(size = 10, color = "black", angle = 0),
        strip.text.x = element_text(size = 15, color = "black", face = "bold")) 
  MTX_var24_table %>% 
    mutate_at(.vars = 6, .funs= scientific_format()) %>% 
  kable(.,caption = "MTX 24 enrichment terms of highly var genes") %>% 
  kable_paper("striped", full_width = FALSE) %>%  
  kable_styling(full_width = FALSE, position = "left",bootstrap_options = c("striped","hover")) %>% 
  scroll_box(width = "100%", height = "400px")

MTX_var24_table %>% 
  filter(source=="KEGG") %>% 
    mutate_at(.vars = 6, .funs= scientific_format()) %>% 
  kable(.,caption = "KEGG MTX 24 hour enrichment terms of highly var genes") %>% 
  
  kable_paper("striped", full_width = FALSE) %>%  
  kable_styling(full_width = FALSE, position = "left",bootstrap_options = c("striped","hover")) %>% 
  scroll_box(width = "100%", height = "400px")


```



## 24 hour TRZ

```{r GO analysis of TRZ24}

# TRZ_var24gost <- gost(query = TRZ_24_var$ENTREZID,
#                   organism = "hsapiens",
#                   significant = FALSE,
#                   ordered_query = TRUE,
#                   domain_scope = "custom",
#                   measure_underrepresentation = FALSE,
#                   evcodes = FALSE,
#                   numeric_ns="ENTREZGENE",
#                   user_threshold = 0.05,
#                   correction_method = "fdr",
#                   custom_bg = backGL$ENTREZID,
#                   sources=c("GO:BP","KEGG"))
# 
# saveRDS(TRZ_var24gost,"data/DEG-GO/var/TRZ_var24gost.RDS")
TRZ_var24gost <- readRDS("data/DEG-GO/var/TRZ_var24gost.RDS")

TRZ_var24p <- gostplot(TRZ_var24gost, capped = FALSE, interactive = TRUE)
TRZ_var24p

TRZ_var24_table <- TRZ_var24gost$result %>% 
  dplyr::select(c(source, term_id, term_name,intersection_size, term_size, p_value))

TRZ_var24_table %>% 
 dplyr::filter(source=="GO:BP") %>% 
    dplyr::select(p_value,term_name,intersection_size) %>%
    slice_min(., n=10 ,order_by=p_value) %>%
    mutate(log_val = -log10(p_value)) %>%
   # slice_max(., n=10,order_by = p_value) %>%
   ggplot(., aes(x = log_val, y =reorder(term_name,p_value), col= intersection_size)) +
    geom_point(aes(size = intersection_size)) +
   geom_vline(xintercept = (-log10(0.05)), col="red")+
    scale_y_discrete(labels = label_wrap(30))+
    guides(col="none", size=guide_legend(title = "# of intersected \n terms"))+
    ggtitle('TRZ24 hour top 10 GO:BP terms') +
    xlab(expression(" -"~log[10]~("adj. p-value")))+
    ylab("GO: BP term")+
      theme_bw()+
    theme(plot.title = element_text(size = rel(1.5), hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.line = element_line(linewidth = 1.5),
        axis.text = element_text(size = 10, color = "black", angle = 0),
        strip.text.x = element_text(size = 15, color = "black", face = "bold")) 
  TRZ_var24_table %>% 
    mutate_at(.vars = 6, .funs= scientific_format()) %>% 
  kable(.,caption = "TRZ 24 enrichment terms of highly var genes") %>% 
  kable_paper("striped", full_width = FALSE) %>%  
  kable_styling(full_width = FALSE, position = "left",bootstrap_options = c("striped","hover")) %>% 
  scroll_box(width = "100%", height = "400px")

TRZ_var24_table %>% 
  filter(source=="KEGG") %>% 
    mutate_at(.vars = 6, .funs= scientific_format()) %>% 
  kable(.,caption = "KEGG TRZ 24 hour enrichment terms of highly var genes") %>% 
  
  kable_paper("striped", full_width = FALSE) %>%  
  kable_styling(full_width = FALSE, position = "left",bootstrap_options = c("striped","hover")) %>% 
  scroll_box(width = "100%", height = "400px")


```



## 24 hour AC shared

```{r GO analysis of AC_share24}
venn24part <- VennDiagram::get.venn.partitions(geneset_24)
AC_share <- venn24part$..values..[[25]]
# AC_share_var24gost <- gost(query = AC_share,
#                   organism = "hsapiens",
#                   significant = FALSE,
#                   ordered_query = TRUE,
#                   domain_scope = "custom",
#                   measure_underrepresentation = FALSE,
#                   evcodes = FALSE,
#                   numeric_ns="ENTREZGENE",
#                   user_threshold = 0.05,
#                   correction_method = "fdr",
#                   custom_bg = backGL$ENTREZID,
#                   sources=c("GO:BP","KEGG"))
# 
# saveRDS(AC_share_var24gost,"data/DEG-GO/var/AC_share_var24gost.RDS")
AC_share_var24gost <- readRDS("data/DEG-GO/var/AC_share_var24gost.RDS")

AC_share_var24p <- gostplot(AC_share_var24gost, capped = FALSE, interactive = TRUE)
AC_share_var24p

AC_share_var24_table <- AC_share_var24gost$result %>% 
  dplyr::select(c(source, term_id, term_name,intersection_size, term_size, p_value))

AC_share_var24_table %>% 
 dplyr::filter(source=="GO:BP") %>% 
    dplyr::select(p_value,term_name,intersection_size) %>%
    slice_min(., n=10 ,order_by=p_value) %>%
    mutate(log_val = -log10(p_value)) %>%
   # slice_max(., n=10,order_by = p_value) %>%
   ggplot(., aes(x = log_val, y =reorder(term_name,p_value), col= intersection_size)) +
    geom_point(aes(size = intersection_size)) +
   geom_vline(xintercept = (-log10(0.05)), col="red")+
    scale_y_discrete(labels = label_wrap(30))+
    guides(col="none", size=guide_legend(title = "# of intersected \n terms"))+
    ggtitle('AC_share24 hour top 10 GO:BP terms') +
    xlab(expression(" -"~log[10]~("adj. p-value")))+
    ylab("GO: BP term")+
      theme_bw()+
    theme(plot.title = element_text(size = rel(1.5), hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.line = element_line(linewidth = 1.5),
        axis.text = element_text(size = 10, color = "black", angle = 0),
        strip.text.x = element_text(size = 15, color = "black", face = "bold")) 
  AC_share_var24_table %>% 
    mutate_at(.vars = 6, .funs= scientific_format()) %>% 
  kable(.,caption = "AC_share 24 enrichment terms of highly var genes") %>% 
  kable_paper("striped", full_width = FALSE) %>%  
  kable_styling(full_width = FALSE, position = "left",bootstrap_options = c("striped","hover")) %>% 
  scroll_box(width = "100%", height = "400px")

AC_share_var24_table %>% 
  filter(source=="KEGG") %>% 
    mutate_at(.vars = 6, .funs= scientific_format()) %>% 
  kable(.,caption = "KEGG AC_share 24 hour enrichment terms of highly var genes") %>% 
  
  kable_paper("striped", full_width = FALSE) %>%  
  kable_styling(full_width = FALSE, position = "left",bootstrap_options = c("striped","hover")) %>% 
  scroll_box(width = "100%", height = "400px")


```



    

## 24 hour TOP2i shared


```{r GO analysis of TOP2i24}

TOP2i <- venn24part$..values..[[17]]
# TOP2i_var24gost <- gost(query = TOP2i,
#                   organism = "hsapiens",
#                   significant = FALSE,
#                   ordered_query = TRUE,
#                   domain_scope = "custom",
#                   measure_underrepresentation = FALSE,
#                   evcodes = FALSE,
#                   numeric_ns="ENTREZGENE",
#                   user_threshold = 0.05,
#                   correction_method = "fdr",
#                   custom_bg = backGL$ENTREZID,
#                   sources=c("GO:BP","KEGG"))
# 
# saveRDS(TOP2i_var24gost,"data/DEG-GO/var/TOP2i_var24gost.RDS")
TOP2i_var24gost <- readRDS("data/DEG-GO/var/TOP2i_var24gost.RDS")

TOP2i_var24p <- gostplot(TOP2i_var24gost, capped = FALSE, interactive = TRUE)
TOP2i_var24p

TOP2i_var24_table <- TOP2i_var24gost$result %>% 
  dplyr::select(c(source, term_id, term_name,intersection_size, term_size, p_value))

TOP2i_var24_table %>% 
 dplyr::filter(source=="GO:BP") %>% 
    dplyr::select(p_value,term_name,intersection_size) %>%
    slice_min(., n=10 ,order_by=p_value) %>%
    mutate(log_val = -log10(p_value)) %>%
   # slice_max(., n=10,order_by = p_value) %>%
   ggplot(., aes(x = log_val, y =reorder(term_name,p_value), col= intersection_size)) +
    geom_point(aes(size = intersection_size)) +
   geom_vline(xintercept = (-log10(0.05)), col="red")+
    scale_y_discrete(labels = label_wrap(30))+
    guides(col="none", size=guide_legend(title = "# of intersected \n terms"))+
    ggtitle('TOP2i 24 hour top 10 GO:BP terms') +
    xlab(expression(" -"~log[10]~("adj. p-value")))+
    ylab("GO: BP term")+
      theme_bw()+
    theme(plot.title = element_text(size = rel(1.5), hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.line = element_line(linewidth = 1.5),
        axis.text = element_text(size = 10, color = "black", angle = 0),
        strip.text.x = element_text(size = 15, color = "black", face = "bold")) 
  TOP2i_var24_table %>% 
    mutate_at(.vars = 6, .funs= scientific_format()) %>% 
  kable(.,caption = "TOP2i 24 enrichment terms of highly var genes") %>% 
  kable_paper("striped", full_width = FALSE) %>%  
  kable_styling(full_width = FALSE, position = "left",bootstrap_options = c("striped","hover")) %>% 
  scroll_box(width = "100%", height = "400px")

TOP2i_var24_table %>% 
  filter(source=="KEGG") %>% 
    mutate_at(.vars = 6, .funs= scientific_format()) %>% 
  kable(.,caption = "KEGG TOP2i 24 hour enrichment terms of highly var genes") %>% 
  
  kable_paper("striped", full_width = FALSE) %>%  
  kable_styling(full_width = FALSE, position = "left",bootstrap_options = c("striped","hover")) %>% 
  scroll_box(width = "100%", height = "400px")


```

## using the Alternative hypothesis = "greater"



```{r alt data wrangling-evalute variance, message=FALSE, warning=FALSE, eval=FALSE}

organized_drugframe <- read.csv("data/organized_drugframe.csv",
                                row.names = 1)

DNR.VEH.24alt <- organized_drugframe %>% 
  select(c(starts_with("Da")&ends_with("24h")),
         c(starts_with("Ve")&ends_with("24h"))) %>%
  rowwise() %>% 
  mutate(data=list(var.test(c_across(starts_with("Da")),c_across(starts_with("Ve")),alternative = "greater"))) 
DOX.VEH.24alt <- organized_drugframe %>% 
  select(c(starts_with("Do")&ends_with("24h")),
         c(starts_with("Ve")&ends_with("24h"))) %>%
 rowwise() %>% 
  mutate(data=list(var.test(c_across(starts_with("Do")),c_across(starts_with("Ve")),alternative = "greater")))

EPI.VEH.24alt <- organized_drugframe %>% 
  select(c(starts_with("Ep")&ends_with("24h")),
         c(starts_with("Ve")&ends_with("24h"))) %>%
 rowwise() %>% 
  mutate(data=list(var.test(c_across(starts_with("Ep")),c_across(starts_with("Ve")),alternative = "greater")))

MTX.VEH.24alt <- organized_drugframe %>% 
  select(c(starts_with("Mi")&ends_with("24h")),
         c(starts_with("Ve")&ends_with("24h"))) %>%
  rowwise() %>% 
  mutate(data=list(var.test(c_across(starts_with("Mi")),c_across(starts_with("Ve")),alternative = "greater")))
TRZ.VEH.24alt <- organized_drugframe %>% 
  select(c(starts_with("Tr")&ends_with("24h")),
         c(starts_with("Ve")&ends_with("24h"))) %>%
  rowwise() %>% 
  mutate(data=list(var.test(c_across(starts_with("Tr")),c_across(starts_with("Ve")),alternative = "greater")))


Var_test_list24alt <- list(DNR.VEH.24alt,DOX.VEH.24alt,EPI.VEH.24alt,MTX.VEH.24alt,TRZ.VEH.24alt)
                      
names(Var_test_list24) <- c('DNR.VEH.24','DOX.VEH.24.alt','EPI.VEH.24.alt','MTX.VEH.24.alt','TRZ.VEH.24.alt')
                    
  
 saveRDS(Var_test_list24,"data/Var_test_list24alt.RDS")   
 
 
```     


```{r alt extract pvalue list}

                 
organized_drugframe <- read.csv("data/organized_drugframe.csv",
                                row.names = 1)

Var_test_list24alt <- readRDS("data/Var_test_list24alt.RDS")
set24 <- names(Var_test_list24alt) 

framefun24alt <- data.frame(ENTREZID=rownames(organized_drugframe))
for (i in 1:length(set24)){
  a <- set24[i]
    s_list<- Var_test_list24alt[[i]][[13]]
  names(s_list) <- rownames(organized_drugframe)
  hold<- map_df(s_list, ~as.data.frame(.x$p.value), .id="ENTREZID")
   framefun24alt[paste0(a)] <- hold$`.x$p.value`
 
}

```

## alt 24 hour histogram of var


```{r plot pvalue as histo alt, echo=TRUE}

framefun24alt %>% 
  pivot_longer(col=!ENTREZID,names_to= "combo", values_to = "p.value") %>% 
  separate(combo, into= c("drug", NA,"time",NA)) %>%
  mutate(drug = factor(drug, levels = c("DOX", "EPI", "DNR","MTX", "TRZ"))) %>% 
  ggplot(.,aes(x=p.value,col=drug,fill=drug))+
  geom_histogram()+
  facet_wrap(~drug)+
  ggtitle("24 hour var.test p.value alternate hypo= greater")
  
```

## Venn 24hr alternative hypo
```{r gene filteringalt, echo=TRUE}
backGL <-read_csv("data/backGL.txt", 
    col_types = cols(...1 = col_skip()))

var24alt<- list <- framefun24alt%>% 
  pivot_longer(col=!ENTREZID,names_to= "combo", values_to = "p.value") %>% 
  separate(combo, into= c("drug", NA,"time",NA)) %>%
  mutate(drug = factor(drug, levels = c("DOX", "EPI", "DNR","MTX", "TRZ"))) %>% 
  filter(p.value<0.05)

DOX_24_vara <- var24alt %>% filter(drug=="DOX") %>% select(ENTREZID)#1534 
EPI_24_vara <- var24alt %>% filter(drug=="EPI")%>% select(ENTREZID)#3147
DNR_24_vara <- var24alt %>% filter(drug=="DNR")%>% select(ENTREZID)#904
MTX_24_vara <- var24alt %>% filter(drug=="MTX")%>% select(ENTREZID)#196
TRZ_24_vara <- var24alt %>% filter(drug=="TRZ")%>% select(ENTREZID)#206

geneset_24alt <- list(DOX_24_vara$ENTREZID, EPI_24_vara$ENTREZID, DNR_24_vara$ENTREZID, MTX_24_vara$ENTREZID, TRZ_24_vara$ENTREZID)
names(geneset_24alt) <- c("DOX_24_var","EPI_24_var","DNR_24_var" ,"MTX_24_var","TRZ_24_var")

ggVennDiagram::ggVennDiagram(geneset_24alt,
              category.names = c("DOX\nn = 1534 ",
                                 "EPI\nn = 31471\n",
                                 "DNR\nn = 904",
                                 "MTX\nn = 196", 
                                "TRZ\nn = 206"),
              show_intersect = FALSE,
              set_color = "black",
              category_size = c(6,6,6,6),
              label = "count",
              label_percent_digit = 1,
              label_size = 4,
              label_alpha = 0,
              label_color = "black",
              edge_lty = "solid", set_size = 4.5)+
  scale_x_continuous(expand = expansion(mult = .3))+
  scale_y_continuous(expand = expansion(mult = .2))+
  scale_color_paletteer_d(palette = "fishualize::Bodianus_pulchellus")+
  scale_fill_distiller(palette="Spectral", direction = -1)+
  labs(title = "24 hour var,alternative hypo =greater, genes p. value <0.05",
       caption = paste("n =", length(unique(var24alt$ENTREZID)),"genes"))+
  
  theme(plot.title = element_text(size = rel(1.6), hjust = 0.5, vjust =1))

```

## ALT 24 hour DOX
```{r alt GO analysis of DOX24}

# altDOX_var24gost <- gost(query = DOX_24_vara$ENTREZID,
#                   organism = "hsapiens",
#                   significant = FALSE,
#                   ordered_query = TRUE,
#                   domain_scope = "custom",
#                   measure_underrepresentation = FALSE,
#                   evcodes = FALSE,
#                   numeric_ns="ENTREZGENE",
#                   user_threshold = 0.05,
#                   correction_method = "fdr",
#                   custom_bg = backGL$ENTREZID,
#                   sources=c("GO:BP","KEGG"))
# 
# saveRDS(altDOX_var24gost,"data/DEG-GO/var/altDOX_var24gost.RDS")
altDOX_var24gost <- readRDS("data/DEG-GO/var/altDOX_var24gost.RDS")

altDOX_var24p <- gostplot(altDOX_var24gost, capped = FALSE, interactive = TRUE)
altDOX_var24p

altDOX_var24_table <- altDOX_var24gost$result %>% 
  dplyr::select(c(source, term_id, term_name,intersection_size, term_size, p_value))

altDOX_var24_table %>% 
 dplyr::filter(source=="GO:BP") %>% 
    dplyr::select(p_value,term_name,intersection_size) %>%
    slice_min(., n=10 ,order_by=p_value) %>%
    mutate(log_val = -log10(p_value)) %>%
   # slice_max(., n=10,order_by = p_value) %>%
   ggplot(., aes(x = log_val, y =reorder(term_name,p_value), col= intersection_size)) +
    geom_point(aes(size = intersection_size)) +
  geom_vline(xintercept = (-log10(0.05)), col="red")+
    scale_y_discrete(labels = label_wrap(30))+
    guides(col="none", size=guide_legend(title = "# of intersected \n terms"))+
    ggtitle('DOX24 hour(alt) top 10 GO:BP terms') +
    xlab(expression(" -"~log[10]~("adj. p-value")))+
    ylab("GO: BP term")+
      theme_bw()+
    theme(plot.title = element_text(size = rel(1.5), hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.line = element_line(linewidth = 1.5),
        axis.text = element_text(size = 10, color = "black", angle = 0),
        strip.text.x = element_text(size = 15, color = "black", face = "bold")) 

altDOX_var24_table %>% 
    mutate_at(.vars = 6, .funs= scientific_format()) %>% 
  kable(.,caption = "DOX 24 hour (alt) enrichment terms of highly var genes") %>% 
  kable_paper("striped", full_width = FALSE) %>%  
  kable_styling(full_width = FALSE, position = "left",bootstrap_options = c("striped","hover")) %>% 
  scroll_box(width = "100%", height = "400px")

altDOX_var24_table %>% 
  filter(source=="KEGG") %>% 
    mutate_at(.vars = 6, .funs= scientific_format()) %>% 
  kable(.,caption = "KEGG DOX 24 hour (alt) enrichment terms of highly var genes") %>% 
  
  kable_paper("striped", full_width = FALSE) %>%  
  kable_styling(full_width = FALSE, position = "left",bootstrap_options = c("striped","hover")) %>% 
  scroll_box(width = "100%", height = "400px")


```



## ALT 24 hour EPI
```{r alt GO analysis of EPI24}

# altEPI_var24gost <- gost(query = EPI_24_vara$ENTREZID,
#                   organism = "hsapiens",
#                   significant = FALSE,
#                   ordered_query = TRUE,
#                   domain_scope = "custom",
#                   measure_underrepresentation = FALSE,
#                   evcodes = FALSE,
#                   numeric_ns="ENTREZGENE",
#                   user_threshold = 0.05,
#                   correction_method = "fdr",
#                   custom_bg = backGL$ENTREZID,
#                   sources=c("GO:BP","KEGG"))
# 
# saveRDS(altEPI_var24gost,"data/DEG-GO/var/altEPI_var24gost.RDS")
altEPI_var24gost <- readRDS("data/DEG-GO/var/altEPI_var24gost.RDS")

altEPI_var24p <- gostplot(altEPI_var24gost, capped = FALSE, interactive = TRUE)
altEPI_var24p

altEPI_var24_table <- altEPI_var24gost$result %>% 
  dplyr::select(c(source, term_id, term_name,intersection_size, term_size, p_value))

altEPI_var24_table %>% 
 dplyr::filter(source=="GO:BP") %>% 
    dplyr::select(p_value,term_name,intersection_size) %>%
    slice_min(., n=10 ,order_by=p_value) %>%
    mutate(log_val = -log10(p_value)) %>%
   # slice_max(., n=10,order_by = p_value) %>%
   ggplot(., aes(x = log_val, y =reorder(term_name,p_value), col= intersection_size)) +
    geom_point(aes(size = intersection_size)) +
  geom_vline(xintercept = (-log10(0.05)), col="red")+
    scale_y_discrete(labels = label_wrap(30))+
    guides(col="none", size=guide_legend(title = "# of intersected \n terms"))+
    ggtitle('EPI24 hour(alt) top 10 GO:BP terms') +
    xlab(expression(" -"~log[10]~("adj. p-value")))+
    ylab("GO: BP term")+
      theme_bw()+
    theme(plot.title = element_text(size = rel(1.5), hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.line = element_line(linewidth = 1.5),
        axis.text = element_text(size = 10, color = "black", angle = 0),
        strip.text.x = element_text(size = 15, color = "black", face = "bold")) 

altEPI_var24_table %>% 
    mutate_at(.vars = 6, .funs= scientific_format()) %>% 
  kable(.,caption = "EPI 24 hour (alt) enrichment terms of highly var genes") %>% 
  kable_paper("striped", full_width = FALSE) %>%  
  kable_styling(full_width = FALSE, position = "left",bootstrap_options = c("striped","hover")) %>% 
  scroll_box(width = "100%", height = "400px")

altEPI_var24_table %>% 
  filter(source=="KEGG") %>% 
    mutate_at(.vars = 6, .funs= scientific_format()) %>% 
  kable(.,caption = "KEGG EPI 24 hour (alt) enrichment terms of highly var genes") %>% 
  
  kable_paper("striped", full_width = FALSE) %>%  
  kable_styling(full_width = FALSE, position = "left",bootstrap_options = c("striped","hover")) %>% 
  scroll_box(width = "100%", height = "400px")


```



## ALT 24 hour DNR
```{r alt GO analysis of DNR24}

# altDNR_var24gost <- gost(query = DNR_24_vara$ENTREZID,
#                   organism = "hsapiens",
#                   significant = FALSE,
#                   ordered_query = TRUE,
#                   domain_scope = "custom",
#                   measure_underrepresentation = FALSE,
#                   evcodes = FALSE,
#                   numeric_ns="ENTREZGENE",
#                   user_threshold = 0.05,
#                   correction_method = "fdr",
#                   custom_bg = backGL$ENTREZID,
#                   sources=c("GO:BP","KEGG"))
# 
# saveRDS(altDNR_var24gost,"data/DEG-GO/var/altDNR_var24gost.RDS")
altDNR_var24gost <- readRDS("data/DEG-GO/var/altDNR_var24gost.RDS")

altDNR_var24p <- gostplot(altDNR_var24gost, capped = FALSE, interactive = TRUE)
altDNR_var24p

altDNR_var24_table <- altDNR_var24gost$result %>% 
  dplyr::select(c(source, term_id, term_name,intersection_size, term_size, p_value))

altDNR_var24_table %>% 
 dplyr::filter(source=="GO:BP") %>% 
    dplyr::select(p_value,term_name,intersection_size) %>%
    slice_min(., n=10 ,order_by=p_value) %>%
    mutate(log_val = -log10(p_value)) %>%
   # slice_max(., n=10,order_by = p_value) %>%
   ggplot(., aes(x = log_val, y =reorder(term_name,p_value), col= intersection_size)) +
    geom_point(aes(size = intersection_size)) +
  geom_vline(xintercept = (-log10(0.05)), col="red")+
    scale_y_discrete(labels = label_wrap(30))+
    guides(col="none", size=guide_legend(title = "# of intersected \n terms"))+
    ggtitle('DNR24 hour(alt) top 10 GO:BP terms') +
    xlab(expression(" -"~log[10]~("adj. p-value")))+
    ylab("GO: BP term")+
      theme_bw()+
    theme(plot.title = element_text(size = rel(1.5), hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.line = element_line(linewidth = 1.5),
        axis.text = element_text(size = 10, color = "black", angle = 0),
        strip.text.x = element_text(size = 15, color = "black", face = "bold")) 

altDNR_var24_table %>% 
    mutate_at(.vars = 6, .funs= scientific_format()) %>% 
  kable(.,caption = "DNR 24 hour (alt) enrichment terms of highly var genes") %>% 
  kable_paper("striped", full_width = FALSE) %>%  
  kable_styling(full_width = FALSE, position = "left",bootstrap_options = c("striped","hover")) %>% 
  scroll_box(width = "100%", height = "400px")

altDNR_var24_table %>% 
  filter(source=="KEGG") %>% 
    mutate_at(.vars = 6, .funs= scientific_format()) %>% 
  kable(.,caption = "KEGG DNR 24 hour (alt) enrichment terms of highly var genes") %>% 
  
  kable_paper("striped", full_width = FALSE) %>%  
  kable_styling(full_width = FALSE, position = "left",bootstrap_options = c("striped","hover")) %>% 
  scroll_box(width = "100%", height = "400px")



```




## ALT 24 hour MTX
```{r alt GO analysis of MTX24}
# 
# altMTX_var24gost <- gost(query = MTX_24_vara$ENTREZID,
#                   organism = "hsapiens",
#                   significant = FALSE,
#                   ordered_query = TRUE,
#                   domain_scope = "custom",
#                   measure_underrepresentation = FALSE,
#                   evcodes = FALSE,
#                   numeric_ns="ENTREZGENE",
#                   user_threshold = 0.05,
#                   correction_method = "fdr",
#                   custom_bg = backGL$ENTREZID,
#                   sources=c("GO:BP","KEGG"))
# 
# saveRDS(altMTX_var24gost,"data/DEG-GO/var/altMTX_var24gost.RDS")
altMTX_var24gost <- readRDS("data/DEG-GO/var/altMTX_var24gost.RDS")

altMTX_var24p <- gostplot(altMTX_var24gost, capped = FALSE, interactive = TRUE)
altMTX_var24p

altMTX_var24_table <- altMTX_var24gost$result %>% 
  dplyr::select(c(source, term_id, term_name,intersection_size, term_size, p_value))

altMTX_var24_table %>% 
 dplyr::filter(source=="GO:BP") %>% 
    dplyr::select(p_value,term_name,intersection_size) %>%
    slice_min(., n=5 ,order_by=p_value) %>%
    mutate(log_val = -log10(p_value)) %>%
   # slice_max(., n=10,order_by = p_value) %>%
   ggplot(., aes(x = log_val, y =reorder(term_name,p_value), col= intersection_size)) +
    geom_point(aes(size = intersection_size)) +
  geom_vline(xintercept = (-log10(0.05)), col="red")+
    scale_y_discrete(labels = label_wrap(30))+
    guides(col="none", size=guide_legend(title = "# of intersected \n terms"))+
    ggtitle('MTX24 hour(alt) top 10 GO:BP terms') +
    xlab(expression(" -"~log[10]~("adj. p-value")))+
    ylab("GO: BP term")+
      theme_bw()+
    theme(plot.title = element_text(size = rel(1.5), hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.line = element_line(linewidth = 1.5),
        axis.text = element_text(size = 10, color = "black", angle = 0),
        strip.text.x = element_text(size = 15, color = "black", face = "bold")) 

altMTX_var24_table %>% 
    mutate_at(.vars = 6, .funs= scientific_format()) %>% 
  kable(.,caption = "MTX 24 hour (alt) enrichment terms of highly var genes") %>% 
  kable_paper("striped", full_width = FALSE) %>%  
  kable_styling(full_width = FALSE, position = "left",bootstrap_options = c("striped","hover")) %>% 
  scroll_box(width = "100%", height = "400px")

altMTX_var24_table %>% 
  filter(source=="KEGG") %>% 
    mutate_at(.vars = 6, .funs= scientific_format()) %>% 
  kable(.,caption = "KEGG MTX 24 hour (alt) enrichment terms of highly var genes") %>% 
  
  kable_paper("striped", full_width = FALSE) %>%  
  kable_styling(full_width = FALSE, position = "left",bootstrap_options = c("striped","hover")) %>% 
  scroll_box(width = "100%", height = "400px")



```





## ALT 24 hour TRZ
```{r alt GO analysis of TRZ24}
# 
# altTRZ_var24gost <- gost(query = TRZ_24_vara$ENTREZID,
#                   organism = "hsapiens",
#                   significant = FALSE,
#                   ordered_query = TRUE,
#                   domain_scope = "custom",
#                   measure_underrepresentation = FALSE,
#                   evcodes = FALSE,
#                   numeric_ns="ENTREZGENE",
#                   user_threshold = 0.05,
#                   correction_method = "fdr",
#                   custom_bg = backGL$ENTREZID,
#                   sources=c("GO:BP","KEGG"))
# 
# saveRDS(altTRZ_var24gost,"data/DEG-GO/var/altTRZ_var24gost.RDS")
altTRZ_var24gost <- readRDS("data/DEG-GO/var/altTRZ_var24gost.RDS")

altTRZ_var24p <- gostplot(altTRZ_var24gost, capped = FALSE, interactive = TRUE)
altTRZ_var24p

altTRZ_var24_table <- altTRZ_var24gost$result %>% 
  dplyr::select(c(source, term_id, term_name,intersection_size, term_size, p_value))

altTRZ_var24_table %>% 
 dplyr::filter(source=="GO:BP") %>% 
    dplyr::select(p_value,term_name,intersection_size) %>%
    slice_min(., n=3 ,order_by=p_value) %>%
    mutate(log_val = -log10(p_value)) %>%
   # slice_max(., n=10,order_by = p_value) %>%
   ggplot(., aes(x = log_val, y =reorder(term_name,p_value), col= intersection_size)) +
    geom_point(aes(size = intersection_size)) +
  geom_vline(xintercept = (-log10(0.05)), col="red")+
    scale_y_discrete(labels = label_wrap(30))+
    guides(col="none", size=guide_legend(title = "# of intersected \n terms"))+
    ggtitle('TRZ24 hour(alt) top 10 GO:BP terms') +
    xlab(expression(" -"~log[10]~("adj. p-value")))+
    ylab("GO: BP term")+
      theme_bw()+
    theme(plot.title = element_text(size = rel(1.5), hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.line = element_line(linewidth = 1.5),
        axis.text = element_text(size = 10, color = "black", angle = 0),
        strip.text.x = element_text(size = 15, color = "black", face = "bold")) 

altTRZ_var24_table %>% 
    mutate_at(.vars = 6, .funs= scientific_format()) %>% 
  kable(.,caption = "TRZ 24 hour (alt) enrichment terms of highly var genes") %>% 
  kable_paper("striped", full_width = FALSE) %>%  
  kable_styling(full_width = FALSE, position = "left",bootstrap_options = c("striped","hover")) %>% 
  scroll_box(width = "100%", height = "400px")

altTRZ_var24_table %>% 
  filter(source=="KEGG") %>% 
    mutate_at(.vars = 6, .funs= scientific_format()) %>% 
  kable(.,caption = "KEGG TRZ 24 hour (alt) enrichment terms of highly var genes") %>% 
  
  kable_paper("striped", full_width = FALSE) %>%  
  kable_styling(full_width = FALSE, position = "left",bootstrap_options = c("striped","hover")) %>% 
  scroll_box(width = "100%", height = "400px")


```




## ALT 24 hour AC shared

```{r GO analysis of altAC_share24}
venn24partalt <- VennDiagram::get.venn.partitions(geneset_24alt)


alt_AC_share <- venn24partalt$..values..[[25]]
# AC_share_var24gosta <- gost(query = alt_AC_share,
#                   organism = "hsapiens",
#                   significant = FALSE,
#                   ordered_query = TRUE,
#                   domain_scope = "custom",
#                   measure_underrepresentation = FALSE,
#                   evcodes = FALSE,
#                   numeric_ns="ENTREZGENE",
#                   user_threshold = 0.05,
#                   correction_method = "fdr",
#                   custom_bg = backGL$ENTREZID,
#                   sources=c("GO:BP","KEGG"))
# 
# saveRDS(AC_share_var24gosta,"data/DEG-GO/var/AC_share_var24gosta.RDS")
AC_share_var24gosta <- readRDS("data/DEG-GO/var/AC_share_var24gost.RDS")

AC_share_var24pa <- gostplot(AC_share_var24gosta, capped = FALSE, interactive = TRUE)
AC_share_var24pa

AC_share_var24_tablea <- AC_share_var24gosta$result %>% 
  dplyr::select(c(source, term_id, term_name,intersection_size, term_size, p_value))

AC_share_var24_tablea %>% 
 dplyr::filter(source=="GO:BP") %>% 
    dplyr::select(p_value,term_name,intersection_size) %>%
    slice_min(., n=10 ,order_by=p_value) %>%
    mutate(log_val = -log10(p_value)) %>%
   # slice_max(., n=10,order_by = p_value) %>%
   ggplot(., aes(x = log_val, y =reorder(term_name,p_value), col= intersection_size)) +
    geom_point(aes(size = intersection_size)) +
   geom_vline(xintercept = (-log10(0.05)), col="red")+
    scale_y_discrete(labels = label_wrap(30))+
    guides(col="none", size=guide_legend(title = "# of intersected \n terms"))+
    ggtitle('alt AC_share24 hour top 10 GO:BP terms') +
    xlab(expression(" -"~log[10]~("adj. p-value")))+
    ylab("GO: BP term")+
      theme_bw()+
    theme(plot.title = element_text(size = rel(1.5), hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.line = element_line(linewidth = 1.5),
        axis.text = element_text(size = 10, color = "black", angle = 0),
        strip.text.x = element_text(size = 15, color = "black", face = "bold")) 
  AC_share_var24_table %>% 
    mutate_at(.vars = 6, .funs= scientific_format()) %>% 
  kable(.,caption = " altAC_share 24 enrichment terms of highly var genes") %>% 
  kable_paper("striped", full_width = FALSE) %>%  
  kable_styling(full_width = FALSE, position = "left",bootstrap_options = c("striped","hover")) %>% 
  scroll_box(width = "100%", height = "400px")

AC_share_var24_table %>% 
  filter(source=="KEGG") %>% 
    mutate_at(.vars = 6, .funs= scientific_format()) %>% 
  kable(.,caption = "alt KEGG AC_share 24 hour enrichment terms of highly var genes") %>% 
  
  kable_paper("striped", full_width = FALSE) %>%  
  kable_styling(full_width = FALSE, position = "left",bootstrap_options = c("striped","hover")) %>% 
  scroll_box(width = "100%", height = "400px")


```




## ALT 24 hour TOP2i shared


```{r GO analysis of altTOP2i24}

TOP2i_alt <- venn24partalt$..values..[[17]]
# TOP2i_var24gosta <- gost(query = TOP2i_alt,
#                   organism = "hsapiens",
#                   significant = FALSE,
#                   ordered_query = TRUE,
#                   domain_scope = "custom",
#                   measure_underrepresentation = FALSE,
#                   evcodes = FALSE,
#                   numeric_ns="ENTREZGENE",
#                   user_threshold = 0.05,
#                   correction_method = "fdr",
#                   custom_bg = backGL$ENTREZID,
#                   sources=c("GO:BP","KEGG"))
# 
# saveRDS(TOP2i_var24gosta,"data/DEG-GO/var/TOP2i_var24gosta.RDS")
TOP2i_var24gosta <- readRDS("data/DEG-GO/var/TOP2i_var24gosta.RDS")

TOP2i_var24pa <- gostplot(TOP2i_var24gosta, capped = FALSE, interactive = TRUE)
TOP2i_var24pa

TOP2i_var24_tablea <- TOP2i_var24gosta$result %>% 
  dplyr::select(c(source, term_id, term_name,intersection_size, term_size, p_value))

TOP2i_var24_tablea %>% 
 dplyr::filter(source=="GO:BP") %>% 
    dplyr::select(p_value,term_name,intersection_size) %>%
    slice_min(., n=10 ,order_by=p_value) %>%
    mutate(log_val = -log10(p_value)) %>%
   # slice_max(., n=10,order_by = p_value) %>%
   ggplot(., aes(x = log_val, y =reorder(term_name,p_value), col= intersection_size)) +
    geom_point(aes(size = intersection_size)) +
   geom_vline(xintercept = (-log10(0.05)), col="red")+
    scale_y_discrete(labels = label_wrap(30))+
    guides(col="none", size=guide_legend(title = "# of intersected \n terms"))+
    ggtitle(' alt TOP2i 24 hour top 10 GO:BP terms') +
    xlab(expression(" -"~log[10]~("adj. p-value")))+
    ylab("GO: BP term")+
      theme_bw()+
    theme(plot.title = element_text(size = rel(1.5), hjust = 0.5),
        axis.title = element_text(size = 15, color = "black"),
        axis.ticks = element_line(linewidth = 1.5),
        axis.line = element_line(linewidth = 1.5),
        axis.text = element_text(size = 10, color = "black", angle = 0),
        strip.text.x = element_text(size = 15, color = "black", face = "bold")) 
  TOP2i_var24_table %>% 
    mutate_at(.vars = 6, .funs= scientific_format()) %>% 
  kable(.,caption = "alt TOP2i 24 enrichment terms of highly var genes") %>% 
  kable_paper("striped", full_width = FALSE) %>%  
  kable_styling(full_width = FALSE, position = "left",bootstrap_options = c("striped","hover")) %>% 
  scroll_box(width = "100%", height = "400px")

TOP2i_var24_tablea %>% 
  filter(source=="KEGG") %>% 
    mutate_at(.vars = 6, .funs= scientific_format()) %>% 
  kable(.,caption = "alt KEGG TOP2i 24 hour enrichment terms of highly var genes") %>% 
  
  kable_paper("striped", full_width = FALSE) %>%  
  kable_styling(full_width = FALSE, position = "left",bootstrap_options = c("striped","hover")) %>% 
  scroll_box(width = "100%", height = "400px")


```









